export default Images = {
  // Icons
  male: require('../assets/images/icons/male.png'),
  female: require('../assets/images/icons/female.png'),
  other: require('../assets/images/icons/other.png'),
  facebook: require('../assets/images/icons/facebook.png'),
  telegram: require('../assets/images/icons/telegram.png'),
  whatsapp: require('../assets/images/icons/whatsapp.png'),
  safe_migrant: require('../assets/images/icons/safe_migrant.png'),
  text_info: require('../assets/images/icons/text_info.png'),
  service_directory: require('../assets/images/icons/service_directory.png'),
  video: require('../assets/images/icons/video.png'),
  agreement: require('../assets/images/icons/agreement.png'),
  workbook: require('../assets/images/icons/workbook.png'),
  passport: require('../assets/images/icons/passport.png'),
  other_doc: require('../assets/images/icons/other_doc.png'),
  travel: require('../assets/images/icons/travel.png'),
  audio: require('../assets/images/icons/speaker.png'),
  active_play: require('../assets/images/icons/speaker_playing.gif'),
  checked: require('../assets/images/icons/checked.png'),
  notification: require('../assets/images/icons/notification.png'),
  home: require('../assets/images/icons/home.png'),
  youtube: require('../assets/images/icons/youtube.png'),
  dotted: require('../assets/images/icons/dotted.png'),
  info: require('../assets/images/icons/info.png'),
  share: require('../assets/images/icons/share.png'),
  doc: require('../assets/images/icons/doc.png'),
  next: require('../assets/images/icons/next.png'),
  left_arrow: require('../assets/images/icons/left_arrow.png'),
  down: require('../assets/images/icons/down.png'),
  rotate: require('../assets/images/icons/rotate.png'),
  vertical_line: require('../assets/images/icons/vertical_line.png'),
  folder: require('../assets/images/icons/folder.png'),
  tick: require('../assets/images/icons/tick.png'),
  user: require('../assets/images/icons/user.png'),
  en: require('../assets/images/icons/en.png'),
  kh: require('../assets/images/icons/kh.png'),

  before_you_go: require('../assets/images/icons/before_you_go.png'),
  your_safety: require('../assets/images/icons/your_safety.png'),
  looking_for_help: require('../assets/images/icons/looking_for_help.png'),
  your_story: require('../assets/images/icons/your_story.png'),
  
  before_you_go_prepare_your_trip: require('../assets/images/icons/before_you_go_prepare_your_trip.png'),
  before_you_go_migration: require('../assets/images/icons/before_you_go_migration.png'),
  before_you_go_coming_home: require('../assets/images/icons/before_you_go_coming_home.png'),
  before_you_go_video: require('../assets/images/icons/before_you_go_video.png'),

  // pre departure list
  six_things_prepare_your_trip: require('../assets/images/icons/six_things_prepare_your_trip.png'),
  pre_departure_list_passport: require('../assets/images/icons/pre_departure_list_passport.png'),
  pre_departure_list_visa: require('../assets/images/icons/pre_departure_list_visa.png'),
  pre_departure_list_work_permit: require('../assets/images/icons/pre_departure_list_work_permit.png'),
  pre_departure_list_destination_links: require('../assets/images/icons/pre_departure_list_destination_links.png'),
  pre_departure_list_contact_with_home: require('../assets/images/icons/pre_departure_list_contact_with_home.png'),
  pre_departure_list_contract: require('../assets/images/icons/pre_departure_list_contract.png'),
  
  // migration
  five_things_prepare_your_trip: require('../assets/images/icons/five_things_prepare_your_trip.png'),
  migration_starting_your_journey: require('../assets/images/icons/migration_starting_your_journey.png'),
  migration_understanding_your_contract: require('../assets/images/icons/migration_understanding_your_contract.png'),
  migration_your_right_as_migrant_worker: require('../assets/images/icons/migration_your_right_as_migrant_worker.png'),

  // coming home
  three_things_to_prepare: require('../assets/images/icons/three_things_to_prepare.png'),
  coming_home_women_migrant_worker: require('../assets/images/icons/coming_home_women_migrant_worker.png'),
  
  // your safety
  your_safety_your_right_and_safety: require('../assets/images/icons/your_safety_your_right_and_safety.png'),
  your_safety_safety_planning: require('../assets/images/icons/your_safety_safety_planning.png'),
  your_safety_videos: require('../assets/images/icons/your_safety_videos.png'),
  
  // your right and safety
  your_right_and_safety_work_permit_1: require('../assets/images/icons/your_right_and_safety_work_permit_1.png'),
  your_right_and_safety_work_permit_2: require('../assets/images/icons/your_right_and_safety_work_permit_2.png'),
  your_right_and_safety_work_permit_3: require('../assets/images/icons/your_right_and_safety_work_permit_3.png'),
  your_right_and_safety_work_permit_4: require('../assets/images/icons/your_right_and_safety_work_permit_4.png'),
  your_right_and_safety_work_permit_5: require('../assets/images/icons/your_right_and_safety_work_permit_5.png'),
  your_right_and_safety_work_permit_6: require('../assets/images/icons/your_right_and_safety_work_permit_6.png'),
  your_right_and_safety_work_permit_7: require('../assets/images/icons/your_right_and_safety_work_permit_7.png'),

  // Logo
  chc_logo: require('../assets/images/logos/chc_logo.png'),
  spotlight: require('../assets/images/logos/spotlight.png'),
  unwomen: require('../assets/images/logos/unwomen.png'),
  logo: require('../assets/images/logos/logo.png'),
  instedd_logo: require('../assets/images/logos/instedd_logo.png'),
  eu: require('../assets/images/logos/eu.png'),
  undp: require('../assets/images/logos/undp.png'),
  global_support: require('../assets/images/logos/global_support.png'),
  gender_equality: require('../assets/images/logos/gender_equality.jpg'),
};
