export default Images = {
  male: require('../assets/images/male.png'),
  female: require('../assets/images/female.png'),
  other: require('../assets/images/other.png'),
  facebook: require('../assets/images/facebook.png'),
  telegram: require('../assets/images/telegram.png'),
  whatsapp: require('../assets/images/whatsapp.png'),
  safe_migrant: require('../assets/images/safe_migrant.png'),
  text_info: require('../assets/images/text_info.png'),
  service_directory: require('../assets/images/service_directory.png'),
  video: require('../assets/images/video.png'),
  logo: require('../assets/images/logo.png'),
  instedd_logo: require('../assets/images/instedd_logo.png'),
  chc_logo: require('../assets/images/chc_logo.png'),
  spotlight: require('../assets/images/spotlight.png'),
  unwomen: require('../assets/images/unwomen.gif'),
  agreement: require('../assets/images/agreement.png'),
  workbook: require('../assets/images/workbook.png'),
  passport: require('../assets/images/passport.png'),
  other_doc: require('../assets/images/other_doc.png'),
};
