export default [
  {
    "id": 1,
    "name": "រៀបចំដំណើររបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/1/before_you_go_prepare_your_trip.png",
    "audio_url": "/uploads/categories/departure/audio/1/prepare_your_trip.mp3",
    "parent_id": null,
    "uuid": "de_001",
    "leaf": false,
    "lft": 1,
    "rgt": 14,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំមុនចេញដំណើរ",
    "hint_image_url": "/uploads/categories/departure/hint_image/1/6_thing_before_you_go_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/1/six_thing_before_you_go_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_prepare_your_trip.png'),
    "audio": "prepare_your_trip.mp3",
    "hint_image": require('../../assets/images/category/6_thing_before_you_go_hint.png'),
    "hint_audio": "six_thing_before_you_go_hint.mp3",
    "offline": true
  },
  {
    "id": 2,
    "name": "លិខិតឆ្លងដែន",
    "description": "<div>លិខិតឆ្លងដែនត្រូវការជាចាំបាច់សម្រាប់ការឆ្លងដែនរបស់អ្នក។ អ្នកអាចស្វែងរកពីរបៀបធ្វើលិខិតឆ្លងដែនពីអាជ្ញាធរមូលដ្ឋាន ឬក្រុមហ៊ុនដែលអ្នកបានចុះឈ្មោះទៅធ្វើការជាមួយ។</div>",
    "image_url": "/uploads/categories/departure/image/2/pre_departure_list_passport.png",
    "audio_url": "/uploads/categories/departure/audio/2/passport.mp3",
    "parent_id": 1,
    "uuid": "de_001_1",
    "leaf": true,
    "lft": 2,
    "rgt": 3,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_passport.png'),
    "audio": "passport.mp3",
    "offline": true
  },
  {
    "id": 3,
    "name": "ទិដ្ឋការ",
    "description": "<div>ទិដ្ឋាការជួយអ្នកឱ្យអ្នករស់នៅ ឬស្នាក់នៅប្រទេសគោលដៅ ដោយមានឯកសារគ្រប់គ្រាន់។ ទិដ្ឋាការអាចមានច្រើនប្រភេទខុសគ្នាពីប្រទេសមួយទៅប្រទេសមួយ។ ទិដ្ឋាការអាចមានដូចជា ទិដ្ឋាការសម្រាប់ដំណើរកម្សាន្ត ទិដ្ឋាការសម្រាប់ស្នាក់នៅរយៈពេលយូរ និងទិដ្ឋាការសម្រាប់ធ្វើការជាដើម។ </div>",
    "image_url": "/uploads/categories/departure/image/3/pre_departure_list_visa.png",
    "audio_url": "/uploads/categories/departure/audio/3/visa.mp3",
    "parent_id": 1,
    "uuid": "de_001_2",
    "leaf": true,
    "lft": 4,
    "rgt": 5,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_visa.png'),
    "audio": "visa.mp3",
    "offline": true
  },
  {
    "id": 4,
    "name": "ប័ណ្ណការងារ",
    "description": "<div>\n  <h2>៣. ប័ណ្ណការងារ</h2>\n  <div>ប័ណ្ណការងារបញ្ជាក់ពីសិទ្ធិរបស់អ្នកក្នុងការធ្វើការងារប្រទេសគោលដៅ។ អ្នកអាចធ្វើប័ណ្ណការងារនេះមុនពេលអ្នកចាកចេញ ឬអាចធ្វើនៅពេលដែលអ្នកទៅដល់ប្រទេសគោលដៅ។</div>\n</div>",
    "image_url": "/uploads/categories/departure/image/4/pre_departure_list_work_permit.png",
    "audio_url": "/uploads/categories/departure/audio/4/work_permit.mp3",
    "parent_id": 1,
    "uuid": "de_001_3",
    "leaf": true,
    "lft": 6,
    "rgt": 7,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_work_permit.png'),
    "audio": "work_permit.mp3",
    "offline": true
  },
  {
    "id": 5,
    "name": "ប្រភេទនៅមធ្យោបាយធ្វើដំណើរ",
    "description": "<div>ស្គាល់ពីប្រទេសគោលដៅរបស់អ្នក និងប្រភេទមធ្យោបាយដែលអ្នកត្រូវប្រើដើម្បីទៅដល់ប្រទេសគោលដៅ</div>",
    "image_url": "/uploads/categories/departure/image/5/pre_departure_list_transportation.png",
    "audio_url": "/uploads/categories/departure/audio/5/transportation.mp3",
    "parent_id": 1,
    "uuid": "de_001_4",
    "leaf": true,
    "lft": 8,
    "rgt": 9,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_transportation.png'),
    "audio": "transportation.mp3",
    "offline": true
  },
  {
    "id": 6,
    "name": "ទំនាក់ទំនងជាមួយអ្នកផ្ទះ",
    "description": "<div>វាជាការសំខាន់ណាស់ដែលអ្នកមានលេខទូរស័ព្ទទំនាក់ទំនង និងមធ្យោបាយផ្សេងៗក្នុងការទំនាក់ទំនងអ្នកផ្ទះ ឬមិត្តជិតស្និទ្ធរបស់អ្នក ដែលអាចឱ្យអ្នកផ្តល់ដំណឹងជាទៀងទាត់ពីដំណើររបស់អ្នក។ </div>",
    "image_url": "/uploads/categories/departure/image/6/pre_departure_list_contact_with_home.png",
    "audio_url": "/uploads/categories/departure/audio/6/contact_with_home.mp3",
    "parent_id": 1,
    "uuid": "de_001_5",
    "leaf": true,
    "lft": 10,
    "rgt": 11,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contact_with_home.png'),
    "audio": "contact_with_home.mp3",
    "offline": true
  },
  {
    "id": 7,
    "name": "លេខ ឬអាស័យដ្ឋានទំនាក់ទំនង",
    "description": "<div>វាជាការសំខាន់ដែលអ្នកស្គាល់ពីអាស័យដ្ឋាន និងលេខទូរស័ព្ទទំនាក់ទំនងកន្លែងធ្វើការ ឬ/នឹង កន្លែងស្នាក់នៅដើម្បីងាយស្រួលក្នុងការស្វែងរកការគាំទ្រនៅពេលចាំបាច់។</div>",
    "image_url": "/uploads/categories/departure/image/7/pre_departure_list_contract_address.png",
    "audio_url": "/uploads/categories/departure/audio/7/contact_address.mp3",
    "parent_id": 1,
    "uuid": "de_001_6",
    "leaf": true,
    "lft": 12,
    "rgt": 13,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contract_address.png'),
    "audio": "contact_address.mp3",
    "offline": true
  },
  {
    "id": 8,
    "name": "ចំណាកស្រុក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/8/before_you_go_migration.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_002",
    "leaf": false,
    "lft": 15,
    "rgt": 26,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំសម្រាប់ចំណាកស្រុក",
    "hint_image_url": "/uploads/categories/departure/hint_image/8/5_thing_migration_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/8/five_thing_migration_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_migration.png'),
    "hint_image": require('../../assets/images/category/5_thing_migration_hint.png'),
    "hint_audio": "five_thing_migration_hint.mp3",
    "offline": true
  },
  {
    "id": 9,
    "name": "ចាប់ផ្តើមចេញដំណើរ",
    "description": "<div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 120px;'>អ្នកអត្ថាធិប្បាយ៖</div>\n    <div style='flex: 1'>\n      សួស្តីបងប្អូនដែលជា អ្នកគំាទ្រអ៊ែប (Fan App) \"\"\"\"ដំណើរឆ្លងដែនរបស់ខ្ញុំ។ យើងសង្ឃឹមថាមកដល់ពេលនេះបងប្អូនបានរៀបចំឯកសារពាក់ព័ន្ធរួចរាល់ និងត្រៀមសម្រាប់ការចេញដំណើរនាពេលដ៏ខ្លីខាងមុខនេះ។  ការធ្វើដំណើរ និងឆ្លងដែន គឺជាផ្នែកសំខាន់មួយនៅក្នុងដំណើរចំណាកស្រុក។\n      <p>សូមស្តាប់នូវការសន្ទនាខាងក្រោមនេះ អំពីបទពិសោធឆ្លងដែនរបស់កុលាបដើម្បីស្វែងរកការងារធ្វើនៅក្រៅប្រទេស។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>សួស្តី កុលាប! សុខសប្បាយជាទេ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>សួស្តី ម៉ាលីស! អរគុណច្រើន ខ្ញុំសុខសប្បាយជាធម្មតាទេ។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំបានដឹងថាកុលាបធ្លាប់មានបទពិសោធចំណាកស្រុកទៅធ្វើការនៅក្រៅប្រទេស។ និយាយចឹងកុលាបទៅធ្វើការនៅប្រទេសណាដែរ? ទៅតាំងពីពេលណា? ហើយបទពិសោធរបស់កុលាបយ៉ាងម៉េចដែរពេលឆ្លងដែន?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div>\n    <div style='flex: 1'>\n      <div>ខ្ញុំទៅធ្វើការនៅប្រទេសថៃ ប្រហែលជាងពីរឆ្នាំហើយ ខ្ញុំទើបមកស្រុកវិញបានប្រមាណជាងពីរអាទិត្យហ្នឹង។</div>\n      <p>ហូ៎ ពេលបួនប្រាំថ្ងៃមុនពេលចេញដំណើរ ខ្ញុំបានសួរបងស្រីជីដូនមួយខ្ញុំដែលធ្លាប់ទៅធ្វើការនៅថៃ និងស្វែងយល់ព័ត៌មានបន្ថែមពីអ្វីដែលត្រូវការសម្រាប់ឆ្លងដែន តាមរយៈហេ្វសបុកផ្លូវការរបស់ក្រសួង និងអង្គការសង្គមស៊ីវិលមានការងារពាក់ព័ន្ធចំណាកស្រុក ស្តាប់វិទ្យុ និងខិតបណ្ណ័ផ្សព្វផ្សាយទាក់ទងនឹងចំណាកស្រុកនានា។</p>\n      <p>ម៉ាលីសឯងចង់ទៅធ្វើការនៅប្រទេសគេមែនទេ? អញ្ចឹងម៉ាលីសត្រូវតែមានលិខិតឆ្លងដែនទិដ្ឋាការ(វីសា) និងឯកសារការងារ ឬប័ណ្ណការងារ ទើបគេអនុញ្ញាត្តិឲ្យយើងចូលប្រទេសគេដើម្បីធ្វើការ វាគឺជាតម្រូវការចំាបាច់។ កាលនោះ ខ្ញុំបានរៀបចំទុកដាក់លិខិតឆ្លងដែន ឯកសារសំខាន់ៗ លុយកាក់ និងរបស់របរប្រើប្រាស់ចាំបាច់ ដូចជាសំឡីអនាម័យ ប្រេងកូឡា ឬប្រេងខ្យល់នៅក្នុងកាបូបស្ពាយជាប់ខ្លួនដើម្បីងាយស្រួលរកពេលត្រូវការបន្ទាន់។ ខ្ញុំមិនដាក់នៅក្នុងកាតាបដាក់ខោអាវ និងគ្រឿងប្រើប្រាស់ទូទៅនោះទេ ព្រោះពេលធ្វើដំណើរកាតាបនោះមិននៅក្បែរយើងទេ។</p>\n      <p>នៅពេលដែលយើងធ្វើដំណើរដល់ព្រំដែន យើងត្រូវបំពេញលិខិតចេញពីខាងប្រទេសយើង និងលិខិតចូលទៅខាងប្រទេសគេ។ លិខិតហ្នឹង គឹយើងត្រូវបំពេញព័ត៌មានឲ្យបានត្រឹមត្រូវ ដូចជាឈ្មោះបុគ្គល ឬឈ្មោះទីកន្លែង និងលេខទូរសព្ទ័ដែលយើងត្រូវទៅក្នុងប្រទេសថៃ។</p>\n      <p>តាមខ្ញុំដឹង នៅពេលយើងចូលទៅប្រទេសណាក៏ដោយ ក៏ត្រូវបំពេញលិខិតចូលដែរ វាជាលក្ខខណ្ឌមិនអាចខ្វះបាន ទោះជិះឡាន ឬយន្តហោះ។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ហូ៎ អីចឹងផង! ខ្ញុំមិនដែលដឹងសោះ។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ម៉ាលីសដឹងទេ  ចំពោះបទពិសោធន៍ខ្ញុំ ខ្ញុំគិតថាសំខាន់ខ្លាំងណាស់ដែលយើងធ្វើដំណើរជាមួយអ្នកដែលយើងស្គាល់ច្បាស់បំផុត អាចជាបងប្អូន ពូមីង ឬអ្នកនៅក្នុងភូមិដែលយើងស្គាល់ប្រវត្តិរបស់គេត្រឹមត្រូវ ព្រោះថានាំឲ្យខ្ញុំមានភាពកក់ក្តៅ នៅពេលមានអ្នករួមដំណើរដែលអាចជឿទុកចិត្តបាន។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ពិតមែនហើយ ពេលទៅជាមួយអ្នកស្គាល់ និងជឿទុកចិត្ត គឺអាចជួយគ្នាបាន។ ចុះពេលកុលាបធ្វើដំណើរយូរទេពីភូមិយើងទៅដល់ទល់ដែន ប្រហែលជាប៉ុន្មានម៉ោង? ជិះទៅអស់លុយប្រហែលប៉ុន្មាន?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>\n      ជិះពីភូមិយើង (ស្រុកបរសេដ្ឋ ខេត្តកំពង់ស្ពី) ទៅដល់ព្រំដែនឡែមដែលខ្ញុំឆ្លងហ្នឹង ប្រហែលជាង ៥ ទៅ ៦ ម៉ោង ព្រោះយើងមានឈប់ខ្លះ ចូលបន្ទប់ទឹក និងញាំអាហារ។  ពីភូមិទៅដល់ព្រំដែនម្នាក់អស់ប្រហែលជាង ៤ ម៉ឺនរៀល ហើយពីព្រំដែនទៅដល់គោលដៅ ជិះប្រហែលជាងពីរម៉ោងទៀត និងអស់ថ្លៃជិះចន្លោះពី ១៥០បាត ទៅ ២០០ បាត។ តាមបទពិសោធខ្ញុំ យើងគួរតែទាក់ទងឲ្យដឹងឡានណា ចេញម៉ោងប៉ុន្មាន? ចេញដំណើរពីទីតាំងណា? តើឡានហ្នឹងទៅដល់ទល់ដែនតែម្តង ឬយ៉ាងណា?\n      <p>បើយើងទៅជាក្រុម យើងគួរទាក់ទងគ្នាកំណត់ម៉ោងពេលចេញដំណើរឲ្យបានច្បាស់ដូចគ្នា យើងគួរតែដឹងពីទីតាំងឡានចេញដំណើរ និងគោលដៅដែលឡាននឹងឈប់ផងដែរ។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អូ៎! ល្អមែនទែន។ ខ្ញុំសុំសួរបញ្ជាក់បន្ថែម អំពីការធ្វើដំណើរពីប្រទេសយើងទៅប្រទេសគេ តើយើងត្រូវធ្វើអ្វីខ្លះ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>អូ៎ ម៉ាលីស មុននឹងទៅដល់ទល់ដែន ខ្ញុំប្រាប់បទពិសោធសំខាន់មួយទៀតដល់ម៉ាលីសឯង។ វាពិតជាសំខាន់ណាស់! យើងត្រូវប្រាប់ពុកម៉ែ និងបងប្អូនជិតស្និត អំពីរយៈពេលនៃការធ្វើដំណើររបស់យើង ប្រហែលជាចំណាយអស់ប៉ុន្មានម៉ោង? ទៅដល់ព្រំដែនប្រហែលម៉ោងប៉ុន្មាន? ហើយឆ្លងពីព្រំដែនទៅដល់ទីកន្លែងដែលយើងត្រូវទៅចំណាយអស់ប្រហែលប៉ុន្មានម៉ោង? អូ៎មួយទៀត លេខទូរស័ព្ទទំនាក់ទំនងរបស់សាច់ញាត្តិជិតស្និតរបស់យើងក៏គួរចំា ឬកត់ត្រាទុក ដែលយើងអាចរកបានភ្លាមៗផងដែរ ពេលយើងជួបបញ្ហាបន្ទាន់ ឬពេលត្រូវការប្រើចាំបាច់។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អរគុណសម្រាប់ការចែករំលែកបទពិសោធក្នុងការធ្វើដំណើរ។ ស្តាប់មើលទៅ គឺសំខាន់ណាស់! ចុះពេលទៅដល់ទល់ដែន កុលាបឯងមានបទពិសោធម៉េចដែរ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>នៅច្រកទល់ដែន គឺមានសកម្មភាពចេញចូលជាហូរហែរ មានការដឹកជញ្ជូនទំនិញ និងមនុស្សឆ្លងកាត់។ ហើយការឆ្លងកាត់ទាំងនោះ មិនមែនចេញចូលស្រេចតែចិត្តនោះទេ ម៉ាលីសអើយ សុទ្ធតែឆ្លងកាត់ការត្រួតពិនិត្យពីខាងប្រទេសយើង បោះត្រាចេញពីខាងមន្ត្រីប៉ូលីសប្រចំាការងារព្រំដែន។ យើងត្រូវរង់ចាំរហូតដល់វេនរបស់យើង ប្រសិនបើមានមនុស្សចេញច្រើន។ ពេលខ្លះ ប៉ូលីសមើលការងារព្រំដែន ក៏សួរយើងមួយ ឬពីរសំនួរផងដែរ តើយើងទៅប្រទេសគេធ្វើអ្វី? ស្នាក់នៅកន្លែងណា?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អូ៎ គេសួរយើងពីកន្លែងដែលស្នាក់នៅដែរមែនទេ? ហើយគេសួរធ្វើអី?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ពិតប្រាកដណាស់ ការដឹងព័ត៌មានកន្លែងស្នាក់នៅរបស់យើងនៅប្រទេសគោលដៅ គឺសំខាន់ណាស់។ នៅពេលយើងជួបប្រទះបញ្ហាអ្វី គេអាចដឹងពីទីកន្លែងត្រូវរកយើង។ ហើយទីតាំងស្នាក់នៅ និងអាស័យដ្ឋានកន្លែងធ្វើការនៅប្រទេសគោលដៅ ខ្ញុំក៏បានប្រាប់ទៅពុកម៉ែ និងសាច់ញាត្តិរបស់ខ្ញុំអោយបានដឹងដែរ។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ចុះកាលពេលកុលាបឯងឆ្លងដែន កុលាបដាក់ទីតាំងនៅណាដែរ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>កាលណុង ខ្ញុំដាក់ទីតាំងស្នាក់នៅជាមួយនឹងបងប្អូនជីដូនមួយខ្ញុំ ដែលគាត់ធ្វើការ និងរស់នៅប្រទេសថៃ ដោយសារគាត់មានទីតាំងជាក់លាក់។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អរគុណចំពោះការចែករំលែកនូវបទពិសោធ ខ្ញុំបានដឹងច្រើនពីអ្វីដែលកុលាប បានធ្វើដើម្បីឆ្លងដែន។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/departure/image/9/journey_start.png",
    "audio_url": "/uploads/categories/departure/audio/9/migration_journey_start.mp3",
    "parent_id": 8,
    "uuid": "de_002_1",
    "leaf": true,
    "lft": 16,
    "rgt": 17,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/journey_start.png'),
    "audio": "migration_journey_start.mp3",
    "offline": true
  },
  {
    "id": 10,
    "name": "ស្វែងយល់អំពីកិច្ចសន្យាការងារ",
    "description": "<div>\n  <div>កិច្ចសន្យាការងារ គឺជាឯកសារស្នូលប្រាប់អ្នកអំពីលក្ខខ័ណ្ឌ អត្ថប្រយោជន៍ និងសិទ្ធិដែលអ្នកទទួលបាន។ មុននឹងចុះកិច្ចសន្យាការងារ ជាការសំខាន់ណាស់ដែលអ្នកគួរពិចារណានូវចំណុចមួយចំនួនដូចជា៖</div>\n  <ul>\n    <li>ជាភាសាដែលអ្នកអាចយល់ពីលក្ខខណ្ឌនៃការងារ រួមទាំងប្រាក់ទទួលបាន អត្ថប្រយោជន៍ផ្សេងៗ ម៉ោងការងារ ថ្ងៃឈប់សម្រាកប្រចាំឆ្នាំ ថ្ងៃឈប់សម្រាកបុណ្យជាតិរបស់ប្រទេសគោលដៅ និងថ្ងៃឈប់សម្រាកពេលឈឺ។</li>\n    <li>ស្ថានភាពការងារដែលមានសុវត្ថិភាព ជាមួយនឹងការការពារសុខភាព និងសន្តិសុខ។</li>\n  </ul>\n  <div>លើសពីនេះ កិច្ចសន្យាការងារ គឺវាសំខាន់ណាស់ ពីព្រោះវាជាឯកសារស្របច្បាប់ដែលសរសេរអំពីភារៈកិច្ច និងកាតព្វកិច្ចរបស់ភាគីនិយោជករបស់អ្នក និងអ្នកជាពលករ។ ត្រូវប្រាកដថា អ្នកបានទទួលកិច្ចសន្យាមួយច្បាប់ ព្រមទំាងអ្នកយល់ច្បាស់ពីខ្លឹមសារនៃកិច្ចសន្យានេះ។ កិច្ចសន្យាត្រូវមានចែងអំពី៖ ឈ្មោះរបស់អ្នក អាស័ន្នដ្ឋានកន្លែងធ្វើការ ឈ្មោះនិយោជក ភារៈកិច្ចរបស់អ្នក ប្រាក់ខែ និងអត្ថប្រយោជន៍របស់អ្នក ម៉ោងធ្វើការ (មិនលើស១២ម៉ោងក្នុងមួយថ្ងៃ រួមទំាងម៉ោងបន្ថែម) វិធីគណនាប្រាក់ឈ្នួលធ្វើការបន្ថែមម៉ោង សិទ្ធឈប់សំរាក ការកាត់ប្រាក់ឈ្នួលណាមួយដែលត្រូវធ្វើ និងការលំអិតអំពីការបញ្ចប់កិច្ចសន្យា។</div>\n</div>",
    "image_url": "/uploads/categories/departure/image/10/migration_understanding_your_contract.png",
    "audio_url": "/uploads/categories/departure/audio/10/migration_understanding_your_contract.mp3",
    "parent_id": 8,
    "uuid": "de_002_2",
    "leaf": true,
    "lft": 18,
    "rgt": 19,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_understanding_your_contract.png'),
    "audio": "migration_understanding_your_contract.mp3",
    "offline": true
  },
  {
    "id": 11,
    "name": "សិទ្ធិពលករចំណាកស្រុក",
    "description": "<div>\n  <div>ទោះបីជាស្ថានភាពចំណាកស្រុករបស់អ្នកយ៉ាងណាក៏ដោយ អ្នកត្រូវតែទទួលបានសិទ្ធិ និងការគាំពារពេញលេញដូចខាងក្រោម៖</div>\n  <ul>\n    <li>សេរីភាពរក្សាអត្តសញ្ញាណរបស់ខ្លួន និងឯកសារសំខាន់ៗផ្សេងៗ</li>\n    <li>សេរីភាពចូលរួមក្នុងសមាគមន៍ដូចជា សហជីព និងសមាគមន៍កម្មករ</li>\n    <li>សេរីភាពរួចផុតពីអំពើហិង្សា និងការបៀតបៀនផ្សេងៗ រួមទាំងការបៀតបៀនផ្លូវភេទទំាងក្នុង និងក្រៅកន្លែងការងារ</li>\n    <li>សិទ្ធិតវ៉ា និងដាក់ពាក្យបណ្តឹងពីបញ្ហានៅកន្លែងការងារ</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/departure/image/11/migration_worker_right.png",
    "audio_url": "/uploads/categories/departure/audio/11/migration_worker_right.mp3",
    "parent_id": 8,
    "uuid": "de_002_3",
    "leaf": true,
    "lft": 20,
    "rgt": 21,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_worker_right.png'),
    "audio": "migration_worker_right.mp3",
    "offline": true
  },
  {
    "id": 12,
    "name": "វប្បធម៌ និងការរស់នៅ",
    "description": "<div>\n  <div>ជារឿងសំខាន់ណាស់ដែលយើងគួរស្វែងយល់ពីវប្បធម៌ក៏ដូចជារបៀបរបបរស់នៅក្នុងប្រទេសគោលដៅ។តោះមកស្តាប់ការសន្ទនារវាងធីតា និងរស្មី។</div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>ធីតា៖</div><div style='flex: 1'>រស្មីមកដល់ស្រុកវិញពីកាលណានឹង? ខ្ញុំកំពុងតែមានគម្រោងទៅក្រៅប្រទេសដើម្បីបានការងារសមរម្យមួយ និងមានប្រាក់ចំណូល។ ចឹង! តើរស្មីអាចប្រាប់ខ្ញុំបានខ្លះទេពីរបៀបរបបរស់នៅក្រៅពីស្រុកយើង?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>រស្មី៖</div><div style='flex: 1'>តាមបទពិសោធន៌របស់ខ្ញុំសំខាន់មែនទែន! បើយើងដឹងថាស្រុកគេនឹងរបៀបរបបរស់នៅបែបម៉េច? គេគោរពសាសនាអ្វីខ្លះ? ពេលទំនេរជាទូទៅគេធ្វើអ្វី? គេទៅដើរលេងនៅកន្លែងណា? គេបរិភោគអាហារបែបណា? សំខាន់ជាងនេះទៀតគេរាក់ទាក់គ្នាបែបណា?​ និងភាសាគន្លឹះសំរាប់ទំនាក់ទំនងមួយចំនួន? ឧទាហរណ៌ នៅប្រទេសម៉ាឡេស៊ី ភាគច្រើនគោរពសាសនាអ៊ីស្លាម ដូចនេះគេអត់ញាំសាច់ជ្រូក ហើយគេតែងតែទៅព្រះវិហារជារៀងរាល់ថ្ងៃសុក្រ ហើយគេស្វាគមន៌គ្នាដោយការនិយាយថាអាសាឡាំវ៉ាលីគុម។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>ធីតា៖</div><div style='flex: 1'>ធ្វើម៉េចទៅទើបខ្ញុំដឹង បើខ្ញុំអត់ដែលទៅនៅនឹងផង?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>រស្មី៖</div><div style='flex: 1'>ធ្វើដូចអ្វីដែលធីតាកំពុងមានចម្ងល់សួរមកខ្ញុំអញ្ចឹង! យើងអាចសួរអ្នកដែលធ្លាប់ទៅប្រទេសដែលយើងចង់ទៅនោះ ហើយពេលទៅដល់ធីតាអាចសាកសួរអ្នកនៅទីនោះបន្ថែមទៀត រឺក៏អាចសង្កេតមើលពីសកម្មភាពរស់នៅប្រចាំថ្ងៃរបស់អ្នកនៅទីនោះ។ បើទៅតាមក្រុមហ៊ុនអ្នកអាចសាកសួរពត៌មានពីបុគ្គលិកក្រុមហ៊ុនក៏បានដែរ។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/departure/image/12/culture_and_living.png",
    "audio_url": "/uploads/categories/departure/audio/12/migration_calture_and_living.mp3",
    "parent_id": 8,
    "uuid": "de_002_4",
    "leaf": true,
    "lft": 22,
    "rgt": 23,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/culture_and_living.png'),
    "audio": "migration_calture_and_living.mp3",
    "offline": true
  },
  {
    "id": 13,
    "name": "គន្លឹះក្នុងការសន្សំប្រាក់",
    "description": "<div>\n  <div>ការសន្សំប្រាក់ពិតជាសំខាន់ខ្លាំងណាស់! ប្រាក់សន្សំរួមចំណែកធ្វើអោយការចំណាកស្រុករបស់អ្នកទទួលបានជោគជ័យ។ ការសន្សំប្រាក់ជួយអោយអ្នកសម្រេចគោលបំណង ដូចជាការបង្កើតមុខរបរ ឬរៀនជំនាញជាក់លាក់សម្រាប់ខ្លួនឯងពេលត្រលប់មកស្រុកវិញ ព្រមទំាងជួយស្តារស្ថានភាព ឬជីវភាពគ្រួសារ ប្រើប្រាស់ក្នុងគ្រាអាសន្នណាមួយ និងជួយគាំទ្រការសិក្សាកូនៗ។</div>\n  <p>ប្រាក់សន្សំ ជាប្រាក់ដែលអ្នកទុកដាច់ដោយឡែកក្រោយពីទូទាត់រាល់ការចំណាយទាំងអស់ ដូចជា ការបង់ថ្លៃផ្ទះ ឬបន្ទប់ជួល ថ្លៃទឹកភ្លើង ការចំណាយលើម្ហូបអាហារប្រចាំថ្ងៃ និងការចំណាយចំាបាច់ផ្សេងៗ ព្រមទំាងប្រាក់ផ្ញើត្រឡប់មកផ្ទះផងដែរ។</p>\n  <p>អ្នកអាចរៀបចំផែនការសន្សំប្រាក់របស់អ្នកដោយគិតលើទឹកប្រាក់ដែលអ្នកចង់ទទួលបានធៀបនឹងរយៈពេលនៃការសន្សំរបស់អ្នក។ ឧទាហរណ៌ អ្នកចង់បានប្រាក់ ៦០០ដុល្លារក្នុងរយៈពេលពីរឆ្នាំ ដូចនេះអ្នកត្រូវដកទុកចំនួន ២៥ដុល្លារ ក្នុងមួយខែជាប្រចាំ។​ អ្នកអាចទុកដាក់លុយនៅកន្លែងដែលអ្នកគិតថាមានសុវត្ថិភាពបំផុត ដូចជា ប្រអប់សុវត្ថិភាព រឺបើកគណនីសន្សំនៅធនាគារណាមួយ។</p>\n</div>",
    "image_url": "/uploads/categories/departure/image/13/money_saving_tip.png",
    "audio_url": "/uploads/categories/departure/audio/13/migration_saving_tip.mp3",
    "parent_id": 8,
    "uuid": "de_002_5",
    "leaf": true,
    "lft": 24,
    "rgt": 25,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/money_saving_tip.png'),
    "audio": "migration_saving_tip.mp3",
    "offline": true
  },
  {
    "id": 14,
    "name": "ដំណើរវិលត្រឡប់",
    "description": null,
    "image_url": "/uploads/categories/departure/image/14/before_you_go_coming_home.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_003",
    "leaf": false,
    "lft": 27,
    "rgt": 34,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចដើម្បីរៀបចំវិលត្រលប់មកស្រុកវិញ",
    "hint_image_url": "/uploads/categories/departure/hint_image/14/3_things_coming_home_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/14/three_thing_coming_home_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_coming_home.png'),
    "hint_image": require('../../assets/images/category/3_things_coming_home_hint.png'),
    "hint_audio": "three_thing_coming_home_hint.mp3",
    "offline": true
  },
  {
    "id": 15,
    "name": "រៀបចំផែនការរបស់អ្នក",
    "description": "<div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ឥឡូវកុលាបឯងត្រលប់មកស្រុកវិញ ខ្ញុំសូមសួរបទពិសោធកុលាបផ្ទាល់ តើយើងគួរធ្វើអ្វីខ្លះនៅពេលយើងសម្រេចចិត្តត្រលប់មករស់នៅក្នុងសហគមន៍យើងវិញ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ខ្ញុំបានសង្កេត និងរៀនសូត្រពីអ្នកមុនខ្លះ ខ្ញុំគិតថាសំខាន់ណាស់ដែលយើងត្រូវគិត និងធ្វើផែនការសម្រាប់ក្រោយពេលធ្វើចំណាកស្រុក។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ផែនការយ៉ាងម៉េចទៅ ខ្ញុំហាក់ដូចជាមិនសូវយល់សោះ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div>\n    <div style='flex: 1'>\n      <div>ផែនការ គឺដូចជាអ្វីដែលយើងរៀបចំមុនពេលធ្វើចំណាកស្រុកអញ្ចឹង។ ឥឡូវជាពេលដែលត្រូវគិត តើរៀបចំអ្វីខ្លះសម្រាប់ត្រលប់ និងរស់នៅក្នុងស្រុកវិញ។ ជាដំបូង គឺរៀបចំការធ្វើដំណើរត្រលប់ទៅស្រុកវិញ។ ខ្ញុំបានប្រាប់ឪពុកម្តាយ និងក្រុមគ្រួសារពីថ្ងៃខែ និងពេលវេលានៃការធ្វើដំណើររបស់ខ្ញុំ។ </div>\n      <p>ហើយខ្ញុំក៏គិតគ្រប់ជ្រុងជ្រោយផងដែរលើការធ្វើដំណើររបស់ខ្ញុំ។ អ៊! ម៉ាលីសឯងមានចាំទេ អំពីការជួញដូរមនុស្សដែលអាចកើតមានគ្រប់ពេល និងទីកន្លែង ដូច្នេះខ្ញុំប្រុងប្រយ័ត្នណាស់ក្នុងការធ្វើដំណើរត្រលប់មកវិញ គឺខ្ញុំមិនធ្វើដំណើរជាមួយអ្នកមិនស្គាល់មុខទេ ហើយខ្ញុំធ្វើដំណើរត្រលប់ជាក្រុមជាមួយបងប្អូន សាច់ញាត្តិដែលខ្ញុំទុកចិត្តបំផុត។</p>\n      <p>រឿងសំខាន់មួយទៀតនោះគឺ ខ្ញុំបានគិតពីមុខរបរ និងការងារអ្វីដែលខ្ញុំចង់ធ្វើ ឬអាចធ្វើបាន។ តើជំនាញអ្វីខ្លះដែលត្រូវការនៅក្នុងសហគមន៍ ឬតំបន់នៅក្បែរស្រុកភូមិរបស់យើង។ </p>\n      <p>បន្ថែមទៀត ខ្ញុំគិត តើខ្ញុំនឹងត្រៀមខ្លួនចូលទៅរស់នៅជាមួយនឹងក្រុមគ្រួសារ និងសហគមន៍យ៉ាងម៉េចដែរ? ព្រោះខ្ញុំបានរស់នៅ និងធ្វើការនៅប្រទេសថៃយូរដែរ។ ខ្ញុំបានគិតថា តើខ្ញុំធ្វើដូចម្តេច ប្រសិនមានការរើសអើងពីសមាជិកគ្រួសារខ្លះ ឬអ្នកភូមិខ្លះនៅក្នុងសហគមន៍?</p>\n      <p>តើខ្ញុំអាចភ្ជាប់ខ្លួនយើងទៅនឹងបណ្តាញគំាទ្រដែលមាននៅក្នុងសហគមន៍យ៉ាងម៉េច?ដើម្បីទទួលបានព័ត៌មានអំពីការងារ និងការគាំពារផ្នែកសង្គមផ្សេងៗ រួមទាំងសេវាអំពើហិង្សាលើស្រ្តីផងដែរ។</p>\n      <p>លើសពីនេះទៀត ខ្ញុំក៏បានចែករំលែកបទពិសោធនៃការទៅធ្វើការនៅប្រទេសថៃជាមួយបងប្អូន និងអ្នកភូមិផ្សេងទៀតដែរ។ ព័ត៌មានពិត ត្រឹមត្រូវពីចំណាកស្រុក គឺជួយឲ្យយើងមានការរៀបចំសម្រាប់ការធ្វើចំណាកស្រុក។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ចុះអារម្មណ៍វិញយ៉ាងម៉េចដែរ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ពេលខ្លះខ្ញុំក៏នឹកពេលវេលា ការចងចាំល្អៗមួយចំនួនផងដែរ។ ជាពិសេសមិត្តរួមការងារជិតស្និតពីរបីនាក់ តែខ្ញុំមិនសោកស្តាយចំពោះការសម្រេចចិត្តរបស់ខ្ញុំទេ។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/departure/image/15/coming_home_make_your_plan.png",
    "audio_url": "/uploads/categories/departure/audio/15/coming_home_prepare_plan.mp3",
    "parent_id": 14,
    "uuid": "de_003_1",
    "leaf": true,
    "lft": 28,
    "rgt": 29,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_make_your_plan.png'),
    "audio": "coming_home_prepare_plan.mp3",
    "offline": true
  },
  {
    "id": 16,
    "name": "ត្រលប់ចូលក្នុងគ្រួសារ",
    "description": "<div>ការត្រលប់មករស់នៅជាមួយគ្រួសារវិញមានទាំងអារម្មណ៍រំភើប និងការបន្សាំខ្លួនចូលទៅក្នុងរបៀបរស់នៅរបស់គ្រួសារអ្នកវិញ។ ជាការចាំបាច់ដែលអ្នកនិយាយប្រាប់ទៅគ្រួសារ រួមមានឳពុកម្តាយ បងប្អូនស្រី ឬមិត្តភក្តិជិតស្និទ្ធរបស់អ្នកពីអារម្មណ៍របស់អ្នក អ្វីដែលអ្នកចង់ធ្វើ និងពីរបៀបរស់នៅប្រចាំថ្ងៃបែបថ្មីរបស់អ្នក។</div>",
    "image_url": "/uploads/categories/departure/image/16/coming_home_women_migrant_worker.png",
    "audio_url": "/uploads/categories/departure/audio/16/coming_home_back_home.mp3",
    "parent_id": 14,
    "uuid": "de_003_2",
    "leaf": true,
    "lft": 30,
    "rgt": 31,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker.png'),
    "audio": "coming_home_back_home.mp3",
    "offline": true
  },
  {
    "id": 17,
    "name": "ស្រ្តីពលករចំណាកស្រុក និងចូលរួមចំណែកក្នុងសេដ្ឋកិច្ច",
    "description": null,
    "image_url": "/uploads/categories/departure/image/17/coming_home_women_migrant_worker_and_economic.png",
    "audio_url": null,
    "parent_id": 14,
    "uuid": "de_003_3",
    "leaf": true,
    "lft": 32,
    "rgt": 33,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker_and_economic.png'),
    "offline": true
  },
  {
    "id": 18,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/18/before_you_go_video.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_004",
    "leaf": true,
    "lft": 35,
    "rgt": 36,
    "type": "Categories::Departure",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/before_you_go_video.png'),
    "offline": true
  },
  {
    "id": 19,
    "name": "សិទ្ធិ និងសុវត្ថិភាពរបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/safety/image/19/your_safety_safety_planning.png",
    "audio_url": "/uploads/categories/safety/audio/19/right_and_your_safety.mp3",
    "parent_id": null,
    "uuid": "sa_001",
    "leaf": false,
    "lft": 37,
    "rgt": 48,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_safety_planning.png'),
    "audio": "right_and_your_safety.mp3",
    "offline": true
  },
  {
    "id": 20,
    "name": "អំពើហិង្សាលើស្រ្តី",
    "description": "<div>\n  <ul>\n    <li>អំពីហិង្សាលើស្ត្រី គឺជាទង្វើអំពើហិង្សាដែលទាក់ទងនឹងយេនឌ័រដែលនាំឲ្យមាន ឬទំនងជាបង្កអោយមានគ្រោះថ្នាក់ ឬការឈឺចាប់ផ្លូវកាយ ផ្លូវភេទ ឬផ្លូវចិត្តដល់ស្រ្តីរួមនឹងការគំរាមកំហែងប្រព្រឹត្តទង្វើទំាងនេះ ការបង្ខិតបង្ខំ ការបំបិទសេរីភាពតាមអំពើចិត្តមិនថាកើតមានឡើងនៅទីសាធារណៈ ឬ ជីវិតឯកជននោះទេ។</li>\n    <li>អំពីហិង្សាលើស្ត្រីគ្រប់ទម្រង់ គឺជាការរំលោភសិទ្ធិស្រ្តី។</li>\n  </ul>\n\n  <h2>ទម្រង់ផ្សេងៗអំពើហិង្សាលើស្រ្តី</h2>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 130px;'>ហិង្សាផ្លូវកាយ៖</div><div style='flex: 1'>វាយដំ ឬដាល់ រុញឲ្យដួល ទះ តប់ គប់ដោយប្រើរបស់ផ្សេងៗ ការខំា ការទាញសក់ ការកាត់ ឬចាក់ ការធ្វើអោយថប់ដង្ហើម និងការដុត ។ល។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 130px;'>ហិង្សាផ្លូវចិត្ត៖</div>\n    <div style='flex: 1'>\n      <ul style='marginTop: 0;'>\n        <li>ជេរប្រមាថ មើលងាយ ឬសម្លុតគំរាមកំហែង</li>\n        <li>មិនគោរព ផ្តល់តម្លៃ និងទំនុកចិត្ត</li>\n        <li>និយាយចំអកបញ្ឈឺចិត្ត និងធ្វើអោយអាម៉ាសមុខ</li>\n        <li>ការបដិសេដលើគំនិត និងយោបល់</li>\n        <li>គ្រប់គ្រង និងបំបិតសិទ្ធសេរីភាព</li>\n        <li>បដិសេធមិនគោរពនូវជំនឿ</li>\n        <li>ការរំពឹងចង់បានច្រើនហួសហេតុ</li>\n        <li>ចេះតែរិះគន់ឥតឈប់ឈរ</li>\n        <li>ទាមទារអ្វីៗដោយមិនសមហេតុផល</li>\n        <li>និយាយចោទប្រកាន់ ស្តីបន្ទោស គំរាម ឬបង្គាប់បញ្ជា</li>\n      </ul>\n    </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 130px;'>ហិង្សាផ្លូវភេទ៖</div>\n    <div style='flex: 1'>ការរំលោភសេពសន្ថវៈ, ការរំលោភសេពសន្ថវៈក្នុងចំណងអាពាហ៍ពិពាហ៍, ស្មន្ធការ (ការរួមភេទជាមួយសាច់ញាតិខ្លួនឯង), បៀតបៀនផ្លូវភេទ, រុកគួនខាងផ្លូវភេទ, បង្ហាញកេរភេទ, ការនិយាយទាក់ទងផ្លូវភេទដែលមិនសមរម្យ ឬសំដែងឥរិយាបទផ្លូវភេទដែលធ្វើឲ្យមានការភ័យខ្លាច, ការប៉ះពាល់រាងកាយ ឬកេរិ៍្តភេទដោយចេតនា, ការបង្ខំឲ្យធ្វើសកម្មភាពផ្លូវភេទ ដូចជាបង្ខំឲ្យរួមភេទតាមមាត់, មើលរឿងអាសអាភាស, ផលិតសម្ភារៈ ឬឧបករណ៍អាសអាភាស ឬមើលសកម្មភាពរួមភេទ ឬលើកទឹកចិត្តអោយប្រព្រឹត្តអាកប្បកិរិយាទាក់ទងនឹងផ្លូវភេទមិនសមរម្យ។ល។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 130px;'>ហិង្សាផ្នែកសេដ្ឋកិច្ច៖</div>\n    <div style='flex: 1'>មិនអនុញ្ញាតឱ្យទទួលបានអាហារ ប្រាក់កាស សម្លៀកបំពាក់ ថ្នាំសង្កូវ ការអប់រំ មិនអនុញ្ញាតឱ្យទៅធ្វើការងារ បង្ខំឱ្យធ្វើការងារ ដកហូតប្រាក់ចំនូលទាំងអស់ ពុំផ្តល់សិទ្ធិកាន់កាប់ទ្រព្យសម្បត្តិ</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំបានឮថាបងប្អូនស្រ្តីពលករចំណាកស្រុកជួបនូវបទពិសោធអំពើហិង្សា តើកុលាបមានដែលឭ ឬឃើញអំពីហិង្សាលើស្រ្តីទេ?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ខ្ញុំបានដឹងរឿងមិត្តរួមការងារជិតស្និតម្នាក់ គឺរស្មី។ រស្មីគាត់រៀបការប្រមាណជាង៣ឆ្នាំហើយ ​ជាមួយនឹងប្តី របស់គាត់ឈ្មោះវិច្ឆិកា ដែលធ្វើការនៅថៃទាំងពីរនាក់។ រស្មីប្រាប់ខ្ញុំថា មុនរៀបការ វិច្ឆិកា គឺប្រចណ្ទ័ខ្លាំងណាស់។ តែពេលណុង៎ រស្មីគិតថាដោយសារតែគាត់ស្រលាញ់នាងខ្លាំងពេក។ ដល់ពេលរៀបការហើយ ប្តីរបស់រស្មី គឺមិនចង់ឲ្យគាត់រាប់អានមិត្តភក្តិ ឬធ្វើការកន្លែងបែកពីគ្នាទេ។ ប៉ុន្តែប្តីរបស់រស្មីវិញ ឲ្យតែបើកប្រាក់ខែម្តងៗ ដឹងតែដើរលេងជាមួយនិងគូរកនរបស់គេដាច់យប់រហូត។ រស្មីបានប្រាប់ខ្ញុំទៀតថា ពេលមួយនោះ ក្រោយពីបើកប្រាក់ខែហើយ ប្តីគេដើរសប្បាយដល់យប់ជ្រៅ ស្រាប់តែមកដល់ផ្ទះរករឿង ថារស្មីមានប្រុសអីណា​ ដោយគ្មានហេតុផលអីសោះ ដល់ពេលនាងប្រកែក ប្តីនាងបានទះកំផ្លៀង និងរុញឲ្យដួល។​ ក្រោយមក វិច្ឆិកាបានមកសុំទោសដែលបានជ្រុលដៃទះកំផ្លៀងប្រពន្ធ និងសន្យាមិនធ្វើអញ្ចឹងទៀតទេ។ មិនបានប្រហែលមួយអាទិត្យផង ប្តីរស្មីបានធ្វើទង្វើនេះដដែល ហើយកាន់តែអាក្រក់ជាងមុនទៅទៀត គឺបានដាល់មុខរស្មីមួយដៃយ៉ាងធ្ងន់។ </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ដល់ថ្នាក់ហ្នឹងផង! វិច្ឆកានោះពិតជាអាក្រក់មែន គេគួរតែត្រូវបានទទួលទោសចំពោះទង្វើហិង្សាដែលគេបានប្រព្រឹត្តិមកលើរស្មី។ តែជាការល្អណាស់ ដែលរស្មីមានមិត្តល្អដូចកុលាបឯង ព្រោះនាងមាន មិត្តល្អដែលអាចទុកចិត្តនិយាយរឿងរ៉ាវក្នុងចិត្តប្រាប់បាន។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/safety/image/20/violence_on_women.png",
    "audio_url": "/uploads/categories/safety/audio/20/violence_on_women.mp3",
    "parent_id": 19,
    "uuid": "sa_001_1",
    "leaf": true,
    "lft": 38,
    "rgt": 39,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/violence_on_women.png'),
    "audio": "violence_on_women.mp3",
    "offline": true
  },
  {
    "id": 21,
    "name": "ការបៀតបៀនផ្លូវភេទ",
    "description": "<div>\n  <div>ការបៀតបៀនផ្លូវភេទ គឺជាទង្វើ ឬឥរិយាបថទាំងឡាយណាដែលមិនចង់បាន មិនស្វាគមន៍ ឬក៏មិនអនុញ្ញាតពាក់ព័ន្ធនឹងផ្លូវភេទដែលធ្វើអោយបុគ្គលម្នាក់ ឬច្រើននាក់មានអារម្មណ៍អាម៉ាស់មុខ ភិតភ័យ ឬអាក់អន់ចិត្ដ។ ការបៀតបៀនផ្លូវភេទមានទម្រង់ខុសគ្នារួមមាន៖ ការបៀតបៀនផ្លូវភេទដោយប្រើអំណាច ពាក្យសម្ដី សំលេង និងការបៀតបៀនផ្លូវភេទដោយកាយវិការ ។</div>\n  <div style='color: red; margin-top: 10px'>ឧទាហរណ៍ ការបៀតបៀនផ្លូវភេទដោយពាក្យសម្ដី</div>\n  <ul>\n    <li>ការប្រើប្រាស់ភាសាមិនសមរម្យ ឬភាសាអាសអាភាស និងនិយាយលេងសើចបែបអាសអាភាស</li>\n    <li>ការហៅមិនសមរម្យទៅកាន់ស្រ្ដីនៅតាមផ្លូវ ឬការប្រើភាសាអាសអាភាសនៅពេលស្រ្តីដើរកាត់</li>\n    <li>ការហូចបែបមិនសមរម្យនៅពេលស្រ្តីដើរកាត់</li>\n    <li>សំណើរ និងការលួងលោមដដែលៗ ដើម្បីបំពេញចំណង់ផ្លូវភេទ ឬការណាត់ជួបក្នុងគោលបំណងផ្លូវភេទ</li>\n    <li>ការនិយាយសម្តីដែលមានលក្ខណៈផ្លូវភេទ (ឧទាហរណ៍៖ ហៅឈ្មោះជាលក្ខណៈផ្លូវភេទ ឬសួរអំពីអត្តសញ្ញាណផ្លូវភេទ ឬការប្រព្រឹត្តខាងផ្លូវភេទ)</li>\n    <li>ការវាយប្រហារឯកជនភាព ទាំងក្នុង និងក្រៅសាលារៀន ឬកន្លែងធ្វើការ (ឧទាហរណ៍៖ការបៀតបៀន ដោយការហៅទៅទូរស័ព្ទ ឬដើរតាមស្រ្ដីនោះដល់ផ្ទះ)</li>\n    <li>ការស្នើដាក់លក្ខខណ្ឌដោះដូរដើម្បីបំពេញចំណង់ផ្លូវភេទផ្ទាល់ខ្លួន ដូចជា ការផ្ទេរ ការដំឡើងឋានៈ ប្រាក់ខែ ឬបន្ដការងារ</li>\n    <li>គំរាមកំហែងវាយធ្វើបាប បង្ខិតបង្ខំ ឬរំលោភផ្លូវភេទ។</li>\n  </ul>\n\n  <div style='color: red;'>ឧទាហរណ៍ ការបៀតបៀនផ្លូវភេទដោយកាយវិការ</div>\n  <ul>\n    <li>ការតាំងបង្ហាញវត្ថុដែលធ្វើឱ្យនឹកឃើញដល់ផ្លូវភេទ ដូចជារូបភាព ទស្សនាវដ្ដី ផ្ទាំងរូបភាព ឬតុក្កតាអាសអាភាស</li>\n    <li>ការសម្លក់សម្លឹង ឬសញ្ញាកាយវិការដែលទាក់ទងនឹងផ្លូវភេទ</li>\n    <li>ការប៉ះ ការថើប ការឱបក្រសោប ការធ្វើសរសៃ ឬការអង្អែលលើរាងកាយដែលមិនអនុញាត</li>\n    <li>ការវាយធ្វើបាប ឬបង្ខិតបង្ខំ និងរំលោភផ្លូវភេទ </li>\n  </ul>\n  <div>ទោះបីជានរណាក៏អាចជាកម្មវត្ថុនៃអំពើបៀតបៀនផ្លូវភេទ ស្រ្តីភាគច្រើនត្រូវបានក្លាយជាជនរងគ្រោះនៃការបៀតបៀនផ្លូវភេទ។ ទម្រង់នៃការការបៀតបៀនផ្លូវភេទ គឺអាចកើតមាននៅគ្រប់ទីកន្លែងទាំងអស់ រួមទាំងកន្លែងធ្វើការ។ នៅកន្លែងធ្វើការ ការបៀតបៀនផ្លូវភេទពេលខ្លះ គឺជាទង្វើមួយដែលជម្រុញឲ្យទទួលយកជាថ្នូរ និងផលប្រយោជន៍ត្រលប់មកវិញ។ ជាក់ស្តែង ការស្នើដាក់លក្ខខណ្ឌដោះដូរដើម្បីបំពេញចំណង់ផ្លូវភេទផ្ទាល់ខ្លួន ដូចជា ការផ្ទេរ ការដំឡើងឋានៈ ប្រាក់ខែ ឬបន្ដការងារ។</div>\n</div>",
    "image_url": "/uploads/categories/safety/image/21/harassment.png",
    "audio_url": "/uploads/categories/safety/audio/21/harassment.mp3",
    "parent_id": 19,
    "uuid": "sa_001_2",
    "leaf": true,
    "lft": 40,
    "rgt": 41,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/harassment.png'),
    "audio": "harassment.mp3",
    "offline": true
  },
  {
    "id": 22,
    "name": "សុខភាពរបស់អ្នក",
    "description": "<div>\n  <div>ការថែទាំសុខភាពរបស់អ្នក គឺមានសារៈសំខាន់ណាស់ ទន្ទឹមនឹងពេលដែលអ្នកខ្វល់ខ្វាយ និងរវល់ជាមួយការងារប្រចាំថ្ងៃ។ </div>\n\n  <ul>\n    <li>មិនមែនជាការខ្មាស់អៀននោះទេក្នុងការនិយាយអំពីបទពិសោធ ឬចំងល់ផ្សេងៗទាក់ទងនឹងការមករដូវរបស់អ្នក។ មិត្តភក្តិជិតស្និទ្ធ ឬបងប្អូនស្រី ឬម្តាយអាចជាមនុស្សដែលគួរឲ្យទុកចិត្ត និងមានអារម្មណ៍សុវត្ថិភាពសម្រាប់អ្នកក្នុងការនិយាយប្រាប់អំពីកង្វល់ ឬការព្រួយបារម្ភផ្សេងៗអំពីការមករដូវរបស់អ្នក។</li>\n    <li>ជាធម្មតា ស្រ្តីមករដូវជារៀងរាល់ចន្លោះពី ២៨ ទៅ ៤០ ថ្ងៃ ដែលជាវដ្តទូទៅ ហើយជារឿងធម្មតា។ រដូវ ទៀង គឺមានន័យថាមកជារៀងរាល់ ២៨ ថ្ងៃម្តង។ ប៉ុន្តែជាករណីកម្រដែលស្រ្តីមករដូវទៀងក្នុងកំឡុងពេល ២៨ថ្ងៃ។ ស្រ្តីខ្លះអាចមករដូវក្នុងកំឡុងពេល ៣០ ថ្ងៃ អ្នកខ្លះ ៣១ ថ្ងៃ ឬអ្នកខ្លះ ៣៥ ថ្ងៃ លើសពីនេះទៀតមានអ្នកខ្លះរហូតដល់ ៤០ ថ្ងៃ។</li>\n    <li>យុវតី និងស្រ្តីមានការព្រួយបារម្ភពីការធ្លាក់សរបស់ពួកគេ។ ជាធម្មតា ស្រ្តីមានការធ្លាក់សមុនមករដូវ និងក្រោយមករដូវ។ នេះជារឿងធម្មតាទេ។ ប៉ុន្តែ ប្រសិនបើការធ្លាក់ស របស់អ្នកមានធុំក្លិន មានពណ៌ដូចជាសំបោរពណ៌លឿង អ្នកគួរតែរកការពិគ្រោះយោបល់ជាមួយគ្រូពេទ្យខាងផ្នែករោគស្រ្តី។ </li>\n    <li>អនាម័យនៅពេលមានរដូវ ដូចជាការលាងសម្អាតឲ្យបានញឹកញាប់ ការប្តូរសំឡីអនាម័យ ឬក្រណាត់ទ្រាប់ ជារៀងរាល់ ៣ ទៅ ៤ ម៉ោង ការហូបអាហារមានបន្លែ ផ្លែឈើ និងហូបទឹកឲ្យបានច្រើន សម្រាកឲ្យបានគ្រប់គ្រាន់ គឺជួយនាំមកនូវសុខភាពបន្តពូជល្អ និងរឹងមាំ។</li>\n    <li>ការស្វែងរកការពិគ្រោះយោបល់ជាមួយគ្រូពេទ្យខាងផ្នែករោគស្រ្តី គឺមានសារៈសំខាន់ណាស់។ កុំភ្លេចណា៎ ការនិយាយពីការមករដូវ ឬសុខភាពបន្តពូជ មិនមែនជារឿងខ្មាស់អៀនទេ!!!</li>\n    <li>អ្នក គឺជាម្ចាស់លើរាងកាយរបស់អ្នក។ អ្នកមានសិទ្ធិធ្វើសេចក្តីសម្រេចចិត្តលើផែនការពន្យារកំណើត និងការកំណត់ចំនួនកូនដែលអ្នកចង់បាន។ មានជម្រើសជាច្រើន ដូចជា ការប្រើប្រាស់ស្រោមអនាម័យ ថ្នាំចាក់ ថ្នាំគ្រាប់ កងដាក់ក្រោមស្បែក និងកងដាក់ក្នុងស្បូន ដែលជាសេវាសុខភាពសាធារណៈ ហើយអាចរកសេវានេះបាន ដូចជា មណ្ឌលសុខភាព ឬមន្ទីរពេទ្យបង្អែកជាដើម ដែលជាមធ្យោបាយមានប្រសិទ្ធិភាពខ្ពស់សម្រាប់ការពន្យាកំណើត។ មធ្យោបាយពន្យាកំណើតបែបធម្មជាតិ ដូចជាតាមរយៈការបំបៅដោះកូន តាមរយៈប្រតិទិន តាមរយៈការដកទឹកកាមចេញ។ ប្រសិទ្ធភាពរបស់វា គឺមិនមានខ្ពស់ទេ ហើយប្រឈមនឹងមានផ្ទៃពោះដោយមិនចង់បាន ឬចៃដន្យ។ </li>\n  </ul>\n\n  <div>កុំភ្លេច ពិគ្រោះយោបល់ជាមួយគ្រូពេទ្យជំនាញ នៅពេលអ្នកចង់ធ្វើផែនការពន្យាកំណើត។ ស្វែងយល់ពីផលប៉ះពាល់ និងប្រសិទ្ធិភាពនៃមធ្យោបាយពន្យារកំណើតនិមួយៗ ជាការចាំបាច់!</div>\n</div>",
    "image_url": "/uploads/categories/safety/image/22/your_health.png",
    "audio_url": "/uploads/categories/safety/audio/22/your_health.mp3",
    "parent_id": 19,
    "uuid": "sa_001_3",
    "leaf": true,
    "lft": 42,
    "rgt": 43,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_health.png'),
    "audio": "your_health.mp3",
    "offline": true
  },
  {
    "id": 23,
    "name": "ស្វែងយល់អំពីការកេងប្រវញ្ច័​និងការជួញដូរ",
    "description": "<div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំបានឮអ្នកភូមិ មេក្រុម មេភូមិ និយាយអីទេថាបងប្អូនស្រ្តីពលករចំណាកស្រុកប្រយត្ន័ត្រូវគេជូញដូរ។ តើយ៉ាងម៉េចវិញ កុលាប? ក្រែងយើងទៅធ្វើការ ចុះហេតុអី្វបានជា គេអាចជួញដូរ ឬកេងប្រវញ្ច័យើងបានយ៉ាងម៉េចវិញ?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>\n      ខ្ញុំធ្លាប់បានចូលរួមវគ្គបណ្តុះបណ្តាលទាក់ទងអំពីជួញដូរមនុស្ស និងការកេងប្រវញ្ច័ ខ្ញុំអាចប្រាប់ម៉ាលីសបានណា។\n      <p>ការជួញដូរមនុស្ស គឺជាការជ្រើសរើស ការដឹកជញ្ជូន ការផ្ទេរ ការឃាត់ទុក ឬការផ្តល់ទីជម្រក តាមមធ្យោបាយគំរាមគំហែង ការប្រើកម្លាំង ទម្រង់ផ្សេងទៀតនៃការបង្ខិតបង្ខំ ការចាប់ ពង្រត់ ការក្លែងបន្លំឯកសារ ការបោកប្រាស់ ការរំលោភបំពានអំណាច ការប្រើតួនាទីរំលោភជនរងគ្រោះ ការឲ្យ ឬទទួលយកកម្រៃ ឬអត្ថប្រយោជន៍ណាមួយដើម្បីសម្រេចបានការព្រមព្រៀងឲ្យមានការត្រួតត្រាលើមនុស្សម្នាក់ទៀត។ ការកេងប្រវ័ញ្ចរួមមាន ការកេងប្រវ័ញ្ចលើពេស្យាកម្មជនដទៃ ឬទម្រង់ផ្សេងៗទៀតនៃការកេងប្រវ័ញ្ចផ្លូវភេទ ពលកម្ម ឬសេវាដោយបង្ខំ ទាសភាព ឬការអនុវត្តន៍ស្រដៀងគ្នានឹង ទាសភាព ទាសករ ឬការដកហូតសរីរាង្គណាមួយ។</p>\n    </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div><div style='flex: 1'>ស្តាប់ទៅ ខ្ញុំដូចជានៅមិនទាន់យល់បានច្បាស់ តើកុលាបអាច ឧទាហរណ៍អ្វីបន្ថែមទៀតមើល។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div><div style='flex: 1'>ខ្ញុំមានរឿងមួយដែលខ្ញុំបានដឹងពីអ្នកធ្វើការជាមួយគ្នា កាលនៅប្រទេសថៃ។ មានស្ត្រីម្នាក់ឈ្មោះចិន្តា គាត់បានដឹងតាមរយៈបុរសម្នាក់នៅក្នុងភូមិ ថានៅប្រទេសថៃមានឳកាសច្រើននឹងអាចរកការងារធ្វើបាន ។ បុរសនោះជាមេខ្យល់នំាមនុស្សទៅធ្វើការនៅរោងចក្រនៅប្រទេសថៃ។ ហើយបានប្រាប់ចិន្តាថា ការចំណាកស្រុកអស់លុយតិចតួចទេ ព្រមទំាងមិនចាំបាច់ចំណេយលើថ្លៃធ្វើឯកសារ ក៏អាចទៅធ្វើការបានដូចគ្នា។ បុរសនោះប្រាប់ចិន្តា កុំឲ្យមានការបារម្ភអ្វីទាំងអស់ គាត់ធានាថាគ្រប់យ៉ាងនឹងគ្មានបញ្ហា ចិន្តានឹងបានការងារធ្វើនៅប្រទេសថៃ ហើយមានប្រាក់ខែខ្ពស់។ លឺសំដីបុរសនោះ ធានាបែបនេះ ចិន្ថាក៏ជឿជាក់។ បុរសនោះតម្រូវឲ្យចិន្តា បង់លុយមួយចំនួន ដើម្បីធ្វើដំណើរទៅធ្វើការទៅប្រទេសថៃ។ ម៉ាលីសដឹងអត់ ថាចិន្តាធ្វើដំណើរបែបណាដើម្បីចូលទៅប្រទេសថៃ?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div><div style='flex: 1'>ប្រាប់មកកុលាប ថាចិន្ថាទៅដោយរបៀបណា? </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div><div style='flex: 1'>ចិន្តាត្រូវលាក់ខ្លួននៅក្នុងឡានដឹកទំនិញដើម្បីឆ្លងដែន។ ពេលគាត់ទៅដល់ស្រាប់តែគេប្រាប់ថា រោងចក្រមិនទាន់បើកឲ្យដំណើរការនោះទេ។ ប៉ុន្តែចិន្តាអាចធ្វើការនៅបារមួយកន្លែងនៅទីក្រុងដ៏ធំនោះ។ ម្ចាស់បារបានផ្តល់កន្លែងស្នាក់នៅឲ្យចិន្តា និងបានដកលិខិតឆ្លងដែនរបស់នាងទុក។ ហើយក៏មិនឲ្យចិន្តាប្រើប្រាស់ទូរស័ព្ទបានដែរ។ 2-3ថ្ងៃក្រោយមក ចិន្ថាក៏បានដឹងថា នារីទាំងអស់នៅទីនោះ គឺត្រូវរួមភេទជាភ្ញៀវដើម្បីបានលុយ ហើយនាងត្រូវបានគេបង្ខំឲ្យធ្វើបែបនោះដូចគ្នាដែរ។ ចិន្តាបានព្យាយាម រត់ចេញពីទីនោះ ប៉ុន្តែនាងត្រូវបានគេ បង្ខាំមិនឲ្យចេញទៅណាបានទេ ហើយម្ចាស់បារនោះ បានប្រាប់ចិន្តាថា នាងបានជំពាក់លុយគេច្រើនណាស់ លើការចំណាយឲ្យនាងបានមកដល់ទីនេះ អញ្ចឹងហើយ នាងត្រូវតែធ្វើការដើម្បីដោះបំណុលទាំងអស់នោះ។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div><div style='flex: 1'>ពិតជាអាក្រក់មែន បោកបញ្ឆោត ភូតកុហក បង្ខំឲ្យចិន្តាធ្វើការដែលនាងមិនចង់ធ្វើ ហើយថានាងជាកូនបំណុលទៀតទាំងដែលចិន្តាមិនធ្លាប់បានខ្ចីលុយថៅកែនោះផង។ ចំណែកឯ បុរសដែលសន្យារកការងារឲ្យចិន្តាធ្វើ និងថាបានប្រាក់ខែច្រើននោះវិញ ពិតជាសំបូរល្បិចគេចកល បោកបញ្ចោត ដើម្បីឲ្យចិន្តាមានការជឿជាក់ បានជាចិន្តាត្រូវបានធ្លាក់ចូលអន្ទាក់នៃការកេងប្រវញ្ច័ផ្លូវភេទបែបនេះ។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div><div style='flex: 1'>ស្តាប់ហើយខឹងយ៉ាងនេះ ប្រហែលជាម៉ាលីសឯងយល់ច្បាស់ហើយមើលទៅ!</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/safety/image/23/understand_exploitation_and_human_traficking.png",
    "audio_url": "/uploads/categories/safety/audio/23/understand_exploitation_and_human_traficking.mp3",
    "parent_id": 19,
    "uuid": "sa_001_4",
    "leaf": true,
    "lft": 44,
    "rgt": 45,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/understand_exploitation_and_human_traficking.png'),
    "audio": "understand_exploitation_and_human_traficking.mp3",
    "offline": true
  },
  {
    "id": 24,
    "name": "សិទ្ធិរបស់អ្នក និងកិច្ចគាំពារ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/24/your_right_and_safety.png",
    "audio_url": null,
    "parent_id": 19,
    "uuid": "sa_001_5",
    "leaf": true,
    "lft": 46,
    "rgt": 47,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_right_and_safety.png'),
    "offline": true
  },
  {
    "id": 25,
    "name": "ផែនការសុវត្ថិភាព",
    "description": null,
    "image_url": "/uploads/categories/safety/image/25/safety_planning_tips.png",
    "audio_url": "/uploads/categories/safety/audio/25/my_body_my_choice_safety_planning_tips.mp3",
    "parent_id": null,
    "uuid": "sa_002",
    "leaf": false,
    "lft": 49,
    "rgt": 58,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_planning_tips.png'),
    "audio": "my_body_my_choice_safety_planning_tips.mp3",
    "offline": true
  },
  {
    "id": 26,
    "name": "ប្រសិនបើអ្នកត្រូវចាកចេញភ្លាមៗ",
    "description": "<div>\n  <div>តើអ្នកនឹងត្រូវការអ្វីខ្លះ ប្រសិនជាអ្នកតម្រូវឱ្យចាកចេញបន្ទាន់?</div>\n\n  <ul>\n    <li>ប្រសិនបើអ្នកត្រូវ ឬសម្រេចចិត្តចាកចេញក្នុងស្ថានភាពបន្ទាន់ វាជារឿងសំខាន់ណាស់ដែលអ្នកត្រូវគិតគូរពីលុយកាក់ ទ្រព្យធន ឯកសារសំខាន់ និងសំភារៈមួយចំនួនដែលអ្នកនឹងត្រូវការ។</li>\n    <li>ការសន្សំលុយ និងលាក់វានៅកន្លែងណាមួយដែលអ្នកអាចយកបានយ៉ាងលឿន និងងាយស្រួល ប្រសិនបើអ្នកត្រូវចាកចេញដោយប្រញាប់។ វាអាចជាលុយ កាតអេធីអ៊ីម (កាតសម្រាប់ដកលុយដោយស្វ័យប្រវត្តិ) ដែលអ្នកត្រូវមានសម្រាប់ចំណាយលើថ្លៃធ្វើដំណើរ និងចំណាយផ្សេងៗ។ គិតដល់មិត្ត ឬអ្នកជិតខាងដែលអាចជួយបញ្ជូលលុយ ទូរស័ព្ទអោយអ្នកនៅពេលត្រូវការប្រើបន្ទាន់។</li>\n    <li>រក្សាទុកអត្តសញ្ញាណប័ណ្ណ ឬលិខិតឆ្លងដែនរបស់អ្នក និងកូននៅកន្លែងដែលលាក់បាំងដែលអាចយកបានភ្លាមៗ។</li>\n    <li>ស្តុកទុកនូវរបស់ដែលអ្នកត្រូវការដូចជា អាហារ សំល្លៀកបំពាក់ជាដើម ដែលអ្នកងាយស្រួលយកបាន។</li>\n    <li>វេចខ្ចប់កាតាបសង្គ្រោះបន្ទាន់សម្រាប់ខ្លួនអ្នក និងលាក់វានៅកន្លែងមានសុវត្ថិភាពនៅផ្ទះអ្នកជិតខាង ឬមិត្តភក្តិដែលអាចជឿទុកចិត្តបាន។</li>\n    <li>បិទការតាមដានទីតាំងក្នុងទូរស័ព្ទ និងឧបករណ៌អេឡិចត្រូនិចផ្សេងៗរបស់អ្នកដែលមានមុខងារស្វែងរកទីតាំងរបស់អ្នក បើសិនជាអ្នកគិតថាត្រូវចាកចេញ។ ត្រូវចង់ចាំថាវាអាចឱ្យអ្នកប្រព្រឹត្តអំពើរំលោភបំពានលើអ្នកតាមដានអ្នកតាមប្រព័ន្ធអនឡាញបាន។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/26/urgent_leave.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_1",
    "leaf": true,
    "lft": 50,
    "rgt": 51,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/urgent_leave.png'),
    "offline": true
  },
  {
    "id": 27,
    "name": "របស់របរដែលត្រូវរៀបចំ",
    "description": "<div>\n  <div>របស់ដែលត្រូវវេចខ្ចប់ក្នុងកាតាបសង្គ្រោះបន្ទាន់របស់អ្នក</div>\n\n  <ul>\n    <li>អត្តសញ្ញាណប័ណ្ណ រួមទាំងរូបថតមួយចំនួន</li>\n    <li>លិខិតឆ្លងដែន លិខិតអនុញ្ញាតការងារ ទិដ្ឋាការ</li>\n    <li>ធានារ៉ាប់រង និងឯកសារសំខាន់ៗផ្សេងៗទៀត។</li>\n    <li>សោរសាគួរសម្រាប់ផ្ទះ ឡាន និងកន្លែងធ្វើការរបស់អ្នក</li>\n    <li>លុយ កាតអេធីអ៊ីម (កាតសម្រាប់ដកលុយដោយស្វ័យប្រវត្តិ)</li>\n    <li>សំល្លៀកបំពាក់បន្ថែម និងខោអាវក្នុង</li>\n    <li>សំឡីអនាម័យ ឬខោទឹកនោមសម្រាប់កូនៗ</li>\n    <li>ខ្សែសាកទូរស័ព្ទ ហើយបើអាច កាតបញ្ចូលទូរស័ព្ទដែលអាចប្រើបានក្នុងពេលមានអាសន្ន</li>\n    <li>ថ្នាំមួយចំនួនដែលអ្នក និងកូនអ្នកប្រើជាប្រចាំ</li>\n    <li>លេខទូរស័ព្ទសំខាន់ៗ</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/27/checklist.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_2",
    "leaf": true,
    "lft": 52,
    "rgt": 53,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/checklist.png'),
    "offline": true
  },
  {
    "id": 28,
    "name": "ចំនុចដែលគួរដឹង",
    "description": "<div>\n  <div>អ្វីដែលអ្នកត្រូវដឹងបើអ្នកជាស្រ្តីពលករចំណាកស្រុក</div>\n\n  <ul>\n    <li>អ្នកមានសិទ្ធទទួលបានសុវត្ថិភាព និងការពារ ទោះបីជាអ្នកមិនមែនជាប្រជាពលរដ្ឋនៅក្នុងប្រទេសអ្នកកំពុងរស់នៅ ឬកំពុងធ្វើការក៏ដោយ។</li>\n    <li>ទាក់ទងក្រុមស្ត្រី ឬអង្គការស្ត្រី ទូរស័ព្ទទាន់ហេតុការណ៌ មន្រ្តីប៉ូលីស ស្ថានទូត សហជីពពាណិជ្ជកម្ម មជ្ឍមណ្ឌលពលករចំណាកស្រុក គ្លីនិកសុខភាព ឬសេវាផ្សេងៗដែលអ្នកត្រូវការ។</li>\n    <li>ស្នើសុំសេវាបកប្រែពេលអ្នកស្វែងរកសេវាទូរស័ព្ទជំនួយ ប៉ូលីស មន្ទីរពេទ្យ ឬសេវាផ្សេងៗទៀត។</li>\n    <li>ភ្ជាប់ទំនាក់ទំនងជាមួយបណ្តាញជួយមិត្ត (ក្រុមស្ត្រី ឬអង្គការស្ត្រី) ដែលអាចផ្តល់ពត៌មាននិងភ្ជាប់អ្នកទៅរកសេវាផ្សេងៗ។</li>\n    <li>រក្សាទុកលេខទូរស័ព្ទស្ថានទូត និងកុងស៊ុល ពួកគេនៅទីនោះដើម្បីជួយអ្នកនៅក្រៅប្រទេស។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/28/thing_need_to_know.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_3",
    "leaf": true,
    "lft": 54,
    "rgt": 55,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/thing_need_to_know.png'),
    "offline": true
  },
  {
    "id": 29,
    "name": "យុទ្ធសាស្រ្តដើម្បីសុវត្ថិភាពផ្សេងទៀត",
    "description": "<div>\n  <div>យុទ្ធសាស្រ្តដើម្បីសុវត្ថិភាពផ្សេងទៀត</div>\n\n  <ul>\n    <li>មានពាក្យសម្ងាត់ ឬសញ្ញាសម្គាល់ ឬឃ្លាសុវត្ថិភាពសំរាប់ប្រើជាមួយមិត្តភក្តិ ឬក្រុមគ្រួសាររបស់អ្នកដើម្បីសុំជំនួយបន្ទាន់ពេលដែលត្រូវការ ដោយមិនចាំបាច់និយាយដោយត្រង់។</li>\n    <li>ស្វែងរកមើលថា តើមានជនណាមួយដែលជនប្រព្រឹត្តគោរព និងមានឥទ្ធិពលលើជនប្រព្រឹត្ត ហើយអាចនិយាយជាមួយគេឱ្យឈប់ប្រើអំពើហិង្សា។ ទោះបីជា រយៈពេលខ្លីក៏ដោយ។</li>\n    <li>កុំនៅស្ងៀម ឬ លាក់បំាង រកសេវាជំនួយពីអាជ្ញាធរមានសមត្ថកិច្ច មន្ត្រីនគរបាល មនុស្សដែលអ្នកជឿ ឬអ្នកដឹកនាំសាសនា ឬអ្នកផ្សេងទៀត។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/29/safety_more_strategy.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_4",
    "leaf": true,
    "lft": 56,
    "rgt": 57,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_more_strategy.png'),
    "offline": true
  },
  {
    "id": 30,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/30/your_safety_videos.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "sa_003",
    "leaf": true,
    "lft": 59,
    "rgt": 60,
    "type": "Categories::Safety",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_videos.png'),
    "offline": true
  }
]
