export default [
  {
    "id": 1,
    "name": "រៀបចំដំណើររបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/1/before_you_go_prepare_your_trip.png",
    "audio_url": "/uploads/categories/departure/audio/1/c1_1_prepare_your_trip.mp3",
    "parent_id": null,
    "uuid": "de_001",
    "leaf": false,
    "lft": 1,
    "rgt": 14,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំមុនចេញដំណើរ",
    "hint_image_url": "/uploads/categories/departure/hint_image/1/6_thing_before_you_go_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/1/c1_1_0_six_thing_before_you_go_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_prepare_your_trip.png'),
    "audio": "c1_1_prepare_your_trip.mp3",
    "hint_image": require('../../assets/images/category/6_thing_before_you_go_hint.png'),
    "hint_audio": "c1_1_0_six_thing_before_you_go_hint.mp3",
    "offline": true
  },
  {
    "id": 2,
    "name": "លិខិតឆ្លងដែន",
    "description": "<div>លិខិតឆ្លងដែនត្រូវការជាចាំបាច់សម្រាប់ការឆ្លងដែនរបស់អ្នក។ អ្នកអាចស្វែងរកពីរបៀបធ្វើលិខិតឆ្លងដែនពីអាជ្ញាធរមូលដ្ឋាន ឬក្រុមហ៊ុនដែលអ្នកបានចុះឈ្មោះទៅធ្វើការជាមួយ។</div>",
    "image_url": "/uploads/categories/departure/image/2/pre_departure_list_passport.png",
    "audio_url": "/uploads/categories/departure/audio/2/c1_1_1_passport.mp3",
    "parent_id": 1,
    "uuid": "de_001_1",
    "leaf": true,
    "lft": 2,
    "rgt": 3,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_passport.png'),
    "audio": "c1_1_1_passport.mp3",
    "offline": true
  },
  {
    "id": 3,
    "name": "ទិដ្ឋាការ",
    "description": "<div>ទិដ្ឋាការជួយអ្នកឱ្យអ្នករស់នៅ ឬស្នាក់នៅប្រទេសគោលដៅ ដោយមានឯកសារគ្រប់គ្រាន់។ ទិដ្ឋាការអាចមានច្រើនប្រភេទខុសគ្នាពីប្រទេសមួយទៅប្រទេសមួយ។ ទិដ្ឋាការអាចមានដូចជា ទិដ្ឋាការសម្រាប់ដំណើរកម្សាន្ត ទិដ្ឋាការសម្រាប់ស្នាក់នៅរយៈពេលយូរ និងទិដ្ឋាការសម្រាប់ធ្វើការជាដើម។ </div>",
    "image_url": "/uploads/categories/departure/image/3/pre_departure_list_visa.png",
    "audio_url": "/uploads/categories/departure/audio/3/c1_1_2_visa.mp3",
    "parent_id": 1,
    "uuid": "de_001_2",
    "leaf": true,
    "lft": 4,
    "rgt": 5,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_visa.png'),
    "audio": "c1_1_2_visa.mp3",
    "offline": true
  },
  {
    "id": 4,
    "name": "ប័ណ្ណការងារ",
    "description": "<div>ប័ណ្ណការងារបញ្ជាក់ពីសិទ្ធិរបស់អ្នកក្នុងការធ្វើការងារប្រទេសគោលដៅ។ អ្នកអាចធ្វើប័ណ្ណការងារនេះមុនពេលអ្នកចាកចេញ ឬអាចធ្វើនៅពេលដែលអ្នកទៅដល់ប្រទេសគោលដៅ។</div>",
    "image_url": "/uploads/categories/departure/image/4/pre_departure_list_work_permit.png",
    "audio_url": "/uploads/categories/departure/audio/4/c1_1_3_work_permit.mp3",
    "parent_id": 1,
    "uuid": "de_001_3",
    "leaf": true,
    "lft": 6,
    "rgt": 7,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_work_permit.png'),
    "audio": "c1_1_3_work_permit.mp3",
    "offline": true
  },
  {
    "id": 5,
    "name": "ប្រភេទមធ្យោបាយធ្វើដំណើរ",
    "description": "<div>ស្គាល់ពីប្រទេសគោលដៅរបស់អ្នក និងប្រភេទមធ្យោបាយដែលអ្នកត្រូវប្រើដើម្បីទៅដល់ប្រទេសគោលដៅ</div>",
    "image_url": "/uploads/categories/departure/image/5/pre_departure_list_transportation.png",
    "audio_url": "/uploads/categories/departure/audio/5/c1_1_4_transportation.mp3",
    "parent_id": 1,
    "uuid": "de_001_4",
    "leaf": true,
    "lft": 8,
    "rgt": 9,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_transportation.png'),
    "audio": "c1_1_4_transportation.mp3",
    "offline": true
  },
  {
    "id": 6,
    "name": "ទំនាក់ទំនងជាមួយអ្នកផ្ទះ",
    "description": "<div>វាជាការសំខាន់ណាស់ដែលអ្នកមានលេខទូរស័ព្ទទំនាក់ទំនង និងមធ្យោបាយផ្សេងៗក្នុងការទំនាក់ទំនងអ្នកផ្ទះ ឬមិត្តជិតស្និទ្ធរបស់អ្នក ដែលអាចឱ្យអ្នកផ្តល់ដំណឹងជាទៀងទាត់ពីដំណើររបស់អ្នក។ </div>",
    "image_url": "/uploads/categories/departure/image/6/pre_departure_list_contact_with_home.png",
    "audio_url": "/uploads/categories/departure/audio/6/c1_1_5_contact_with_home.mp3",
    "parent_id": 1,
    "uuid": "de_001_5",
    "leaf": true,
    "lft": 10,
    "rgt": 11,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contact_with_home.png'),
    "audio": "c1_1_5_contact_with_home.mp3",
    "offline": true
  },
  {
    "id": 7,
    "name": "លេខ ឬអាស័យដ្ឋានទំនាក់ទំនង",
    "description": "<div>វាជាការសំខាន់ដែលអ្នកស្គាល់ពីអាស័យដ្ឋាន និងលេខទូរស័ព្ទទំនាក់ទំនងកន្លែងធ្វើការ ឬ/នឹង កន្លែងស្នាក់នៅដើម្បីងាយស្រួលក្នុងការស្វែងរកការគាំទ្រនៅពេលចាំបាច់។</div>",
    "image_url": "/uploads/categories/departure/image/7/pre_departure_list_contract_address.png",
    "audio_url": "/uploads/categories/departure/audio/7/c1_1_6_contact_address.mp3",
    "parent_id": 1,
    "uuid": "de_001_6",
    "leaf": true,
    "lft": 12,
    "rgt": 13,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contract_address.png'),
    "audio": "c1_1_6_contact_address.mp3",
    "offline": true
  },
  {
    "id": 8,
    "name": "ចំណាកស្រុក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/8/before_you_go_migration.png",
    "audio_url": "/uploads/categories/departure/audio/8/c1_2_migration_20.mp3",
    "parent_id": null,
    "uuid": "de_002",
    "leaf": false,
    "lft": 15,
    "rgt": 26,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំសម្រាប់ចំណាកស្រុក",
    "hint_image_url": "/uploads/categories/departure/hint_image/8/5_thing_migration_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/8/c1_2_0_five_thing_migration_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_migration.png'),
    "audio": "c1_2_migration_20.mp3",
    "hint_image": require('../../assets/images/category/5_thing_migration_hint.png'),
    "hint_audio": "c1_2_0_five_thing_migration_hint.mp3",
    "offline": true
  },
  {
    "id": 9,
    "name": "ចាប់ផ្តើមចេញដំណើរ",
    "description": "<div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 120px;'>អ្នកអត្ថាធិប្បាយ៖</div>\n    <div style='flex: 1'>សួស្តី​បងប្អូន​ដែល​ជា​ អ្នកគំាទ្រ​អ៊ែប​ (Fan App)​ “ដំណើរឆ្លងដែនរបស់ខ្ញុំ”។ យើង​សង្ឃឹម​ថា​មក​ដល់​ពេល​នេះ​​បងប្អូន​បាន​រៀប​ចំ​ឯកសារ​ពាក់ព័ន្ធ​រួច​រាល់​ និង​ត្រៀម​សម្រាប់​ការ​ចេញ​ដំណើរ​នាពេល​ដ៏​ខ្លី​ខាង​មុខ​នេះ។  ការ​ធ្វើ​ដំណើរ​ និង​ឆ្លង​ដែន​​ គឺ​ជា​ផ្នែក​សំខាន់​មួយ​នៅ​ក្នុង​ដំណើរ​ចំណាក​ស្រុក។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>សូម​ស្តាប់​នូវ​ការ​សន្ទនា​ខាង​ក្រោម​នេះ​ អំពី​បទពិសោធ​ឆ្លង​ដែន​របស់​កុលាប​ដើម្បី​ស្វែងរក​ការងារ​ធ្វើ​នៅ​ក្រៅ​ប្រទេស។​</div>\n  <div style='display: flex;'>\n    <div style='display: flex; flex-direction: row'>សួស្តី កុលាប! សុខ​សប្បាយ​ជា​ទេ?​</div>\n    <div style='display: flex; flex-direction: row'>សួស្តី ម៉ាលីស! អរគុណ​ច្រើន​ ខ្ញុំ​សុខ​សប្បាយ​ជា​ធម្មតា​ទេ។​</div>\n  <div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំ​បាន​ដឹង​ថា​កុលាប​ធ្លាប់​មាន​បទពិសោធ​ចំណាក​ស្រុក​ទៅ​ធ្វើ​ការ​នៅ​ក្រៅ​ប្រទេស។​ និយាយ​ចឹង​កុលាប​ទៅ​ធ្វើ​ការ​នៅ​ប្រទេស​ណា​ដែរ? ទៅ​តាំង​ពី​ពេល​ណា?​​ ហើយ​បទពិសោធ​របស់​កុលាប​យ៉ាង​ម៉េច​ដែរ​ពេល​ឆ្លង​ដែន?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div>\n    <div style='flex: 1'>\n      <div>ខ្ញុំ​ទៅ​ធ្វើ​ការ​នៅ​ប្រទេស​ថៃ​ ប្រហែល​ជាង​ពីរឆ្នាំ​ហើយ​ ខ្ញុំ​ទើប​មក​ស្រុក​វិញ​បាន​ប្រមាណ​ជាង​ពីរអាទិត្យ​ហ្នឹង។</div>\n      <p>ហូ៎ ពេល​បួនប្រាំថ្ងៃ​មុន​ពេល​ចេញ​ដំណើរ​ ខ្ញុំ​បាន​សួរ​បង​ស្រី​ជីដូនមួយ​ខ្ញុំ​ដែល​ធ្លាប់​ទៅ​ធ្វើ​ការ​នៅ​ថៃ​ និង​ស្វែង​យល់​ព័ត៌មាន​បន្ថែម​ពី​អ្វី​ដែល​ត្រូវ​ការ​សម្រាប់​ឆ្លង​ដែន​ តាម​រយៈ​ហេ្វសបុក​ផ្លូវការ​របស់​ក្រសួង​ និង​អង្គការ​សង្គម​ស៊ីវិល​មាន​ការងារ​ពាក់ព័ន្ធ​ចំណាក​ស្រុក​ ស្តាប់​វិទ្យុ​ និង​ខិតប័ណ្ណ​ផ្សព្វផ្សាយ​ទាក់​ទង​នឹង​ចំណាក​ស្រុក​នានា។</p>\n      <p>ម៉ាលីស​ឯង​ចង់​ទៅ​ធ្វើ​ការ​នៅ​ប្រទេស​គេ​មែន​ទេ?​ អញ្ចឹង​ម៉ាលីស​ត្រូវ​តែ​មាន​លិខិត​ឆ្លងដែន​ទិដ្ឋាការ(វីសា)​ និង​ឯកសារ​ការងារ​ ឬ​ប័ណ្ណ​ការងារ​ ទើប​គេ​អនុញ្ញាត្តិ​ឲ្យ​យើង​ចូល​ប្រទេស​គេ​ដើម្បី​ធ្វើ​ការ​ វា​គឺ​ជា​តម្រូវការ​ចំាបាច់។​​ កាល​នោះ​ ខ្ញុំ​បាន​រៀបចំ​ទុក​ដាក់​លិខិត​ឆ្លងដែន​ ឯកសារ​សំខាន់ៗ​ លុយកាក់​ និង​របស់របរ​ប្រើ​ប្រាស់​ចាំបាច់​ ដូចជា​សំឡី​អនាម័យ​ ប្រេង​កូឡា​ ឬប្រេង​ខ្យល់​នៅ​ក្នុង​កាបូប​ស្ពាយ​ជាប់​ខ្លួន​ដើម្បី​ងាយស្រួល​រក​ពេល​ត្រូវ​ការបន្ទាន់។​ ខ្ញុំ​មិន​ដាក់​នៅ​ក្នុង​កាតាប​ដាក់​ខោអាវ​ និង​គ្រឿង​ប្រើ​ប្រាស់​ទូទៅ​នោះ​ទេ​ ព្រោះ​ពេល​ធ្វើ​ដំណើរ​កាតាប​នោះ​មិន​នៅ​ក្បែរ​យើងទេ។​</p>\n      <p>នៅ​ពេល​ដែល​យើង​ធ្វើ​ដំណើរ​ដល់​ព្រំដែន​ យើង​ត្រូវ​បំពេញ​លិខិត​ចេញ​ពី​ខាង​ប្រទេស​យើង​ និង​លិខិត​ចូល​ទៅ​ខាង​ប្រទេសគេ។​ លិខិតហ្នឹង​ គឺយើង​ត្រូវ​បំពេញ​ព័ត៌មាន​ឲ្យ​បាន​ត្រឹមត្រូវ​ ដូច​ជាឈ្មោះ​បុគ្គល​ ឬឈ្មោះ​ទីកន្លែង​ និង​លេខ​ទូរស័ព្ទ​ដែល​យើង​ត្រូវ​ទៅ​ក្នុង​ប្រទេសថៃ។</p>\n      <p>តាមខ្ញុំដឹង​ នៅ​ពេល​យើង​ចូល​ទៅ​ប្រទេស​ណា​ក៏ដោយ​ ក៏​ត្រូវ​បំពេញ​លិខិត​ចូល​ដែរ​ វា​ជា​លក្ខខណ្ឌ​មិន​អាច​ខ្វះ​បាន​ ទោះ​ជិះ​ឡាន​ ឬយន្តហោះ។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ហូ៎ អីចឹងផង! ខ្ញុំមិនដែលដឹងសោះ។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ម៉ាលីស​ដឹងទេ​ ចំពោះ​បទពិសោធ​ខ្ញុំ​ ខ្ញុំគិត​ថា​​សំខាន់​ខ្លាំង​ណាស់​ដែល​យើង​ធ្វើ​ដំណើរ​ជាមួយ​អ្នក​ដែល​យើង​ស្គាល់​ច្បាស់​បំផុត​ អាច​ជា​បងប្អូន​ ពូមីង​ ឬអ្នក​នៅ​ក្នុង​ភូមិ​ដែល​យើង​ស្គាល់​ប្រវត្តិ​របស់​គេ​ត្រឹមត្រូវ​ ព្រោះ​ថា​នាំ​ឲ្យ​ខ្ញុំ​មាន​ភាព​កក់ក្តៅ​ នៅ​ពេល​មាន​អ្នក​រួម​ដំណើរ​ដែល​អាច​ជឿ​ទុកចិត្ត​បាន។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ពិត​មែន​ហើយ ពេល​ទៅ​ជាមួយ​អ្នកស្គាល់ និងជឿ​ទុកចិត្ត​ គឺ​អាច​ជួយ​គ្នា​បាន។ ចុះ​ពេល​កុលាប​ធ្វើ​ដំណើរ​យូរ​ទេ​ពី​ភូមិ​យើង​ទៅ​ដល់​ទល់ដែន​ ប្រហែល​ជាប៉ុន្មាន​ម៉ោង?​ ជិះ​ទៅ​អស់​លុយ​ប្រហែល​ប៉ុន្មាន?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ជិះ​ពី​ភូមិ​យើង​ (ស្រុកបរសេដ្ឋ​ ខេត្តកំពង់ស្ពឺ) ទៅ​​ដល់​ព្រំដែនឡែម​ដែល​ខ្ញុំ​ឆ្លង​ហ្នឹង ប្រហែល​ជាង​ ៥ ទៅ ៦ ម៉ោង​ ព្រោះ​យើង​មាន​ឈប់​ខ្លះ​ ចូល​បន្ទប់ទឹក​ និងញាំអាហារ។​  ពី​ភូមិ​ទៅ​ដល់​ព្រំដែន​ម្នាក់​អស់​ប្រហែល​ជាង ៤​ ម៉ឺនរៀល​ ហើយ​ពី​ព្រំដែន​ទៅ​ដល់​គោលដៅ​ ជិះ​ប្រហែល​ជាង​ពីរម៉ោង​ទៀត​​ និងអស់​ថ្លៃ​ជិះ​ចន្លោះពី​ ១៥០បាត ទៅ ២០០ បាត។ តាម​បទពិសោធ​ខ្ញុំ​ យើង​គួរ​តែ​ទាក់ទង​ឲ្យ​ដឹង​ឡាន​ណា ចេញ​ម៉ោងប៉ុន្មាន? ចេញ​ដំណើរ​ពីទីតាំងណា? តើ​ឡាន​ហ្នឹង​ទៅ​ដល់​ទល់ដែន​តែម្តង ឬយ៉ាងណា?\n      <p>បើ​យើង​ទៅ​ជាក្រុម​ យើង​គួរ​ទាក់ទង​គ្នា​កំណត់​ម៉ោង​ពេល​ចេញ​ដំណើរ​ឲ្យ​បាន​ច្បាស់​ដូចគ្នា​ យើង​គួរ​តែ​ដឹង​ពី​ទីតាំង​ឡាន​ចេញ​ដំណើរ និង​គោលដៅ​ដែល​ឡាន​នឹង​ឈប់​ផងដែរ។</p>\n    </div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អូ៎! ល្អ​មែនទែន។ ខ្ញុំ​សុំ​សួរ​បញ្ជាក់​បន្ថែម​ អំពី​ការធ្វើ​ដំណើរ​ពី​ប្រទេស​យើង​ទៅ​ប្រទេស​គេ តើ​យើង​ត្រូវ​ធ្វើអ្វីខ្លះ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>អូ៎ ម៉ាលីស មុន​នឹង​ទៅ​ដល់​ទល់ដែន​ ខ្ញុំ​ប្រាប់​បទពិសោធ​សំខាន់​មួយ​ទៀត​ដល់​ម៉ាលីសឯង។ វា​ពិត​ជា​សំខាន់​ណាស់! យើង​ត្រូវ​ប្រាប់​ពុកម៉ែ​ និងបងប្អូន​ជិតស្និត​ អំពី​រយៈ​ពេល​នៃ​ការធ្វើ​ដំណើរ​របស់​យើង​ ប្រហែល​ជា​ចំណាយ​អស់​ប៉ុន្មានម៉ោង? ទៅ​ដល់​ព្រំដែន​ប្រហែល​ម៉ោង​ប៉ុន្មាន? ហើយ​ឆ្លង​ពី​ព្រំដែន​ទៅ​ដល់​ទីកន្លែង​ដែល​យើង​ត្រូវ​ទៅ​ចំណាយ​អស់​ប្រហែល​ប៉ុន្មានម៉ោង? អូ៎មួយទៀត​ លេខទូរស័ព្ទ​ទំនាក់​ទំនង​របស់​សាច់ញាត្តិ​ជិតស្និត​របស់​យើង​ក៏គួរចំា​ ឬកត់ត្រា​ទុក​ ដែល​យើង​អាច​រក​បាន​ភ្លាមៗ​ផងដែរ​ ពេល​យើង​ជួប​បញ្ហា​បន្ទាន់​ ឬពេល​ត្រូវការ​ប្រើចាំបាច់។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អរគុណ​សម្រាប់​ការ​ចែក​រំលែក​បទពិសោធ​ក្នុង​ការ​ធ្វើដំណើរ។ ស្តាប់​មើល​ទៅ​ គឺសំខាន់​ណាស់! ចុះ​ពេល​ទៅ​ដល់​ទល់ដែន​ កុលាប​ឯង​មាន​បទពិសោធ​ម៉េចដែរ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>នៅ​ច្រក​ទល់ដែន​ គឺ​មាន​សកម្មភាព​ចេញ​ចូល​ជា​ហូរហែរ​ មាន​ការ​ដឹកជញ្ជូន​ទំនិញ​ និងមនុស្ស​ឆ្លងកាត់។​ ហើយ​ការ​ឆ្លងកាត់​ទាំង​នោះ​ មិន​មែន​ចេញ​ចូល​ស្រេច​តែ​ចិត្ត​នោះ​ទេ ម៉ាលីស​អើយ​ សុទ្ធ​តែ​ឆ្លងកាត់​ការ​ត្រួត​ពិនិត្យ​ពី​ខាង​ប្រទេស​យើង​ បោះត្រា​ចេញ​ពី​ខាង​មន្ត្រីប៉ូលីស​ប្រចំាការងារ​ព្រំដែន។ យើង​ត្រូវ​រង់ចាំ​រហូត​ដល់​វេន​របស់​យើង ប្រសិន​បើ​មាន​មនុស្ស​ចេញ​ច្រើន។ ពេល​ខ្លះ ប៉ូលីស​មើល​ការងារ​ព្រំដែន​ ក៏​សួរ​យើង​មួយ ឬពីរ​សំនួរ​ផង​ដែរ​ តើ​យើង​ទៅ​ប្រទេស​គេ​ធ្វើអ្វី? ស្នាក់​នៅ​កន្លែង​ណា?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អូ៎ គេ​សួរ​យើង​ពី​កន្លែង​ដែល​ស្នាក់​នៅ​ដែរ​មែនទេ? ហើយ​គេ​សួរ​ធ្វើអី?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ពិត​ប្រាកដ​ណាស់​ ការ​ដឹង​ព័ត៌មាន​កន្លែង​ស្នាក់នៅ​របស់​យើង​នៅ​ប្រទេស​គោលដៅ​ គឺ​សំខាន់​ណាស់​។ នៅ​ពេល​យើង​ជួប​ប្រទះ​បញ្ហា​អ្វី គេ​អាច​ដឹង​ពី​ទីកន្លែង​ត្រូវ​រក​យើង។ ហើយ​ទី​តាំង​ស្នាក់នៅ​ និង​អាស័យដ្ឋាន​កន្លែង​ធ្វើការ​នៅ​ប្រទេស​គោលដៅ​ ខ្ញុំ​ក៏​បាន​ប្រាប់​ទៅ​ពុកម៉ែ​ និងសាច់ញាត្តិ​របស់ខ្ញុំ​អោយ​បាន​ដឹងដែរ។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ចុះ​កាល​ពេល​កុលាប​ឯង​ឆ្លងដែន​ កុលាប​ដាក់​ទីតាំង​នៅ​ណា​ដែរ?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>កាល​ណុង ខ្ញុំ​ដាក់​ទី​តាំង​ស្នាក់នៅ​ជាមួយ​នឹង​បងប្អូន​ជីដូនមួយខ្ញុំ ដែល​គាត់​ធ្វើការ​ និង​រស់នៅ​ប្រទេសថៃ​ ដោយសារ​គាត់​មាន​ទី​តាំង​ជាក់លាក់។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>អរគុណ​ចំពោះ​ការ​ចែករំលែក​នូវ​បទពិសោធ​ ខ្ញុំ​បាន​ដឹង​ច្រើន​ពី​អ្វី​ដែល​កុលាប​បាន​ធ្វើ​ដើម្បី​ឆ្លងដែន។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/departure/image/9/journey_start.png",
    "audio_url": "/uploads/categories/departure/audio/9/c1_2_1_migration_journey_start.mp3",
    "parent_id": 8,
    "uuid": "de_002_1",
    "leaf": true,
    "lft": 16,
    "rgt": 17,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/journey_start.png'),
    "audio": "c1_2_1_migration_journey_start.mp3",
    "offline": true
  },
  {
    "id": 10,
    "name": "ស្វែងយល់អំពីកិច្ចសន្យាការងារ",
    "description": "<div>\n  <div>កិច្ចសន្យាការងារ គឺជាឯកសារស្នូលប្រាប់អ្នកអំពីលក្ខខណ្ឌ អត្ថប្រយោជន៍ និងសិទ្ធិដែលអ្នកទទួលបាន។ មុននឹងចុះកិច្ចសន្យាការងារ ជាការសំខាន់ណាស់ដែលអ្នកគួរពិចារណានូវចំណុចមួយចំនួនដូចជា៖</div>\n  <ul>\n    <li>ជាភាសាដែលអ្នកអាចយល់ពីលក្ខខណ្ឌនៃការងារ រួមទាំងប្រាក់ទទួលបាន អត្ថប្រយោជន៍ផ្សេងៗ ម៉ោងការងារ ថ្ងៃឈប់សម្រាកប្រចាំឆ្នាំ ថ្ងៃឈប់សម្រាកបុណ្យជាតិរបស់ប្រទេសគោលដៅ និងថ្ងៃឈប់សម្រាកពេលឈឺ។</li>\n    <li>ស្ថានភាពការងារដែលមានសុវត្ថិភាព ជាមួយនឹងការការពារសុខភាព និងសន្តិសុខ។</li>\n  </ul>\n  <div>លើសពីនេះ កិច្ចសន្យាការងារ គឺវាសំខាន់ណាស់ ពីព្រោះវាជាឯកសារស្របច្បាប់ដែលសរសេរអំពីភារៈកិច្ច និងកាតព្វកិច្ចរបស់ភាគីនិយោជករបស់អ្នក និងអ្នកជាពលករ។ ត្រូវប្រាកដថា អ្នកបានទទួលកិច្ចសន្យាមួយច្បាប់ ព្រមទំាងអ្នកយល់ច្បាស់ពីខ្លឹមសារនៃកិច្ចសន្យានេះ។ កិច្ចសន្យាត្រូវមានចែងអំពី៖ ឈ្មោះរបស់អ្នក អាស័យដ្ឋានកន្លែងធ្វើការ ឈ្មោះនិយោជក ភារៈកិច្ចរបស់អ្នក ប្រាក់ខែ និងអត្ថប្រយោជន៍របស់អ្នក ម៉ោងធ្វើការ (មិនលើស១២ម៉ោងក្នុងមួយថ្ងៃ រួមទំាងម៉ោងបន្ថែម) វិធីគណនាប្រាក់ឈ្នួលធ្វើការបន្ថែមម៉ោង សិទ្ធិ​ឈប់សំរាក ការកាត់ប្រាក់ឈ្នួលណាមួយដែលត្រូវធ្វើ និងការលំអិតអំពីការបញ្ចប់កិច្ចសន្យា។</div>\n</div>",
    "image_url": "/uploads/categories/departure/image/10/migration_understanding_your_contract.png",
    "audio_url": "/uploads/categories/departure/audio/10/c1_2_2_migration_understanding_your_contract.mp3",
    "parent_id": 8,
    "uuid": "de_002_2",
    "leaf": true,
    "lft": 18,
    "rgt": 19,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_understanding_your_contract.png'),
    "audio": "c1_2_2_migration_understanding_your_contract.mp3",
    "offline": true
  },
  {
    "id": 11,
    "name": "សិទ្ធិពលករចំណាកស្រុក",
    "description": "<div>\n  <div>ទោះបីជាស្ថានភាពចំណាកស្រុករបស់អ្នកយ៉ាងណាក៏ដោយ អ្នកត្រូវតែទទួលបានសិទ្ធិ និងការគាំពារពេញលេញដូចខាងក្រោម៖</div>\n  <ul>\n    <li>សេរីភាព​រក្សា​អត្តសញ្ញាណ​របស់​ខ្លួន​ និង​ឯកសារ​សំខាន់ៗ​ផ្សេងៗ​</li>\n    <li>សេរីភាពចូលរួមក្នុងសមាគមន៍ដូចជា សហជីព និងសមាគមន៍កម្មករ</li>\n    <li>សេរីភាព​រួច​ផុត​ពី​អំពើ​ហិង្សា​ និង​ការ​បៀត​បៀន​ផ្សេងៗ​ ​រួម​ទាំង​ការ​បៀត​បៀន​ផ្លូវ​ភេទ​ទំាង​ក្នុង​ និង​ក្រៅ​កន្លែង​ការងារ​</li>\n    <li>សិទ្ធិតវ៉ា និងដាក់ពាក្យបណ្តឹងពីបញ្ហានៅកន្លែងការងារ</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/departure/image/11/migration_worker_right.png",
    "audio_url": "/uploads/categories/departure/audio/11/c1_2_3_migration_worker_right.mp3",
    "parent_id": 8,
    "uuid": "de_002_3",
    "leaf": true,
    "lft": 20,
    "rgt": 21,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_worker_right.png'),
    "audio": "c1_2_3_migration_worker_right.mp3",
    "offline": true
  },
  {
    "id": 12,
    "name": "វប្បធម៌ និងការរស់នៅ",
    "description": "<div>\n  <div>ជារឿងសំខាន់ណាស់ដែលយើងគួរស្វែងយល់ពីវប្បធម៌ក៏ដូចជារបៀបរបបរស់នៅក្នុងប្រទេសគោលដៅ។​ តោះមកស្តាប់ការសន្ទនារវាងធីតា និងរស្មី៖</div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>ធីតា៖</div><div style='flex: 1'>រស្មីមកដល់ស្រុកវិញពីកាលណានឹង? ខ្ញុំកំពុងតែមានគម្រោងទៅក្រៅប្រទេសដើម្បីបានការងារសមរម្យមួយ និងមានប្រាក់ចំណូល។ ចឹង! តើរស្មីអាចប្រាប់ខ្ញុំបានខ្លះទេពីរបៀបរបបរស់នៅក្រៅពីស្រុកយើង?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>រស្មី៖</div><div style='flex: 1'>តាមបទពិសោធរបស់ខ្ញុំសំខាន់មែនទែន! បើយើងដឹងថាស្រុកគេនឹងរបៀបរបបរស់នៅបែបម៉េច? គេគោរពសាសនាអ្វីខ្លះ? ពេលទំនេរជាទូទៅគេធ្វើអ្វី? គេទៅដើរលេងនៅកន្លែងណា? គេបរិភោគអាហារបែបណា? សំខាន់ជាងនេះទៀតគេរាក់ទាក់គ្នាបែបណា?​ និងភាសាគន្លឹះសំរាប់ទំនាក់ទំនងមួយចំនួន? ឧទាហរណ៍ នៅប្រទេសម៉ាឡេស៊ី ភាគច្រើនគោរពសាសនាអ៊ីស្លាម ដូចនេះគេ​អត់​ញុំាសាច់ជ្រូក ហើយគេតែងតែទៅព្រះវិហារជារៀងរាល់ថ្ងៃសុក្រ ហើយគេស្វាគមន៍គ្នាដោយការនិយាយថាអាសាឡាំវ៉ាលីគុម។</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>ធីតា៖</div><div style='flex: 1'>ធ្វើម៉េចទៅទើបខ្ញុំដឹង បើខ្ញុំអត់ដែលទៅនៅនឹងផង?</div>\n  </div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 60px;'>រស្មី៖</div><div style='flex: 1'>ធ្វើដូចអ្វីដែលធីតាកំពុងមានចម្ងល់សួរមកខ្ញុំអញ្ចឹង! យើងអាចសួរអ្នកដែលធ្លាប់ទៅប្រទេសដែលយើងចង់ទៅនោះ ហើយពេលទៅដល់ធីតាអាចសាកសួរអ្នកនៅទីនោះបន្ថែមទៀត រឺក៏អាចសង្កេតមើលពីសកម្មភាពរស់នៅប្រចាំថ្ងៃរបស់អ្នកនៅទីនោះ។ បើទៅតាមក្រុមហ៊ុនអ្នកអាចសាកសួរព័ត៌មានពីបុគ្គលិកក្រុមហ៊ុនក៏បានដែរ។</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/departure/image/12/culture_and_living.png",
    "audio_url": "/uploads/categories/departure/audio/12/c1_2_4_migration_calture_and_living.mp3",
    "parent_id": 8,
    "uuid": "de_002_4",
    "leaf": true,
    "lft": 22,
    "rgt": 23,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/culture_and_living.png'),
    "audio": "c1_2_4_migration_calture_and_living.mp3",
    "offline": true
  },
  {
    "id": 13,
    "name": "គន្លឹះក្នុងការសន្សំប្រាក់",
    "description": "<div>\n  <div>ការសន្សំ​ប្រាក់​ពិត​ជា​សំខាន់​ខ្លាំង​ណាស់!​ ប្រាក់​សន្សំ​រួម​ចំណែក​ធ្វើ​អោយ​ការ​ចំណាក​ស្រុក​របស់​អ្នក​ទទួល​បាន​ ជោគជ័យ។​ ការ​សន្សំ​ប្រាក់​ជួយ​អោយ​អ្នក​សម្រេច​គោលបំណង​ ដូច​ជា​ការ​បង្កើត​មុខ​របរ​ ឬរៀន​ជំនាញ​ជាក់លាក់​សម្រាប់​ខ្លួន​ឯង​ពេល​ត្រលប់​មក​ស្រុក​វិញ​ ព្រម​ទំាង​ជួយ​ស្តារ​ស្ថានភាព​ ឬជីវភាព​គ្រួសារ​ ប្រើ​ប្រាស់​ក្នុង​គ្រាអាសន្ន​ណា​មួយ​ និង​ជួយ​គាំទ្រ​ការ​សិក្សា​កូនៗ។</div>\n  <p>ប្រាក់សន្សំ​ ជា​ប្រាក់​ដែល​អ្នក​ទុក​ដាច់​ដោយ​ឡែក​ក្រោយ​ពី​ទូទាត់​រាល់​ការ​ចំណាយ​ទាំង​អស់​ ដូច​ជា​ ការ​បង់​ថ្លៃ​ផ្ទះ​ ឬបន្ទប់​ជួល​ ថ្លៃ​ទឹក​ភ្លើង​ ការ​ចំណាយ​លើ​ម្ហូប​អាហារ​ប្រចាំ​ថ្ងៃ​ និង​ការ​ចំណាយ​ចំា​បាច់​ផ្សេងៗ​ ព្រម​ទំាង​ប្រាក់​ផ្ញើ​ត្រឡប់​មក​ផ្ទះ​ផង​ដែរ។</p>\n  <p>អ្នក​អាច​រៀបចំ​ផែនការ​សន្សំ​ប្រាក់​របស់​អ្នក​ដោយ​គិត​លើ​ទឹក​ប្រាក់​ដែល​អ្នក​ចង់​ទទួល​បាន​ធៀប​នឹង​រយៈ​ពេល​នៃ​ការ​សន្សំ​របស់​អ្នក។​ ឧទាហរណ៍​ អ្នក​ចង់​បាន​ប្រាក់​ ៦០០ដុល្លារ​ក្នុង​រយៈ​ពេល​ពីរឆ្នាំ​ ដូច​នេះ​អ្នក​ត្រូវ​ដក​ទុក​ចំនួន​ ២៥ដុល្លារ​ ក្នុង​មួយខែ​ជា​ប្រចាំ។​​ អ្នក​អាច​ទុក​ដាក់​លុយ​នៅ​កន្លែង​ដែល​អ្នក​គិត​ថា​មាន​សុវត្ថិភាព​បំផុត​ ដូចជា​ ប្រអប់​សុវត្ថិភាព​ ឬ​ បើក​គណនី​សន្សំ​នៅ​ធនាគារ​ណាមួយ។</p>\n</div>",
    "image_url": "/uploads/categories/departure/image/13/money_saving_tip.png",
    "audio_url": "/uploads/categories/departure/audio/13/c1_2_5_migration_saving_tip.mp3",
    "parent_id": 8,
    "uuid": "de_002_5",
    "leaf": true,
    "lft": 24,
    "rgt": 25,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/money_saving_tip.png'),
    "audio": "c1_2_5_migration_saving_tip.mp3",
    "offline": true
  },
  {
    "id": 14,
    "name": "ដំណើរវិលត្រឡប់",
    "description": null,
    "image_url": "/uploads/categories/departure/image/14/before_you_go_coming_home.png",
    "audio_url": "/uploads/categories/departure/audio/14/c1_3_retruning_trip.mp3",
    "parent_id": null,
    "uuid": "de_003",
    "leaf": false,
    "lft": 27,
    "rgt": 34,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចដើម្បីរៀបចំវិលត្រលប់មកស្រុកវិញ",
    "hint_image_url": "/uploads/categories/departure/hint_image/14/3_things_coming_home_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/14/c1_3_0_three_thing_coming_home_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_coming_home.png'),
    "audio": "c1_3_retruning_trip.mp3",
    "hint_image": require('../../assets/images/category/3_things_coming_home_hint.png'),
    "hint_audio": "c1_3_0_three_thing_coming_home_hint.mp3",
    "offline": true
  },
  {
    "id": 15,
    "name": "រៀបចំផែនការរបស់អ្នក",
    "description": "<div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ឥឡូវកុលាបឯងត្រលប់មកស្រុកវិញ ខ្ញុំសូមសួរបទពិសោធកុលាបផ្ទាល់ តើយើងគួរធ្វើអ្វីខ្លះនៅពេលយើងសម្រេចចិត្តត្រលប់មករស់នៅក្នុងសហគមន៍យើងវិញ?</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ខ្ញុំបានសង្កេត និងរៀនសូត្រពីអ្នកមុនខ្លះ ខ្ញុំគិតថាសំខាន់ណាស់ដែលយើងត្រូវគិត​ និងធ្វើផែនការសម្រាប់ក្រោយពេលធ្វើចំណាកស្រុក។</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ផែនការយ៉ាងម៉េចទៅ​ ខ្ញុំហាក់ដូចជាមិនសូវយល់សោះ?</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>កុលាប៖</div>\n <div style='flex: 1'>\n <p>ផែនការ គឺដូចជាអ្វីដែលយើងរៀបចំមុនពេលធ្វើចំណាកស្រុកអញ្ចឹង។ ឥឡូវជាពេលដែលត្រូវគិត តើរៀបចំអ្វីខ្លះសម្រាប់ត្រលប់ និងរស់នៅក្នុងស្រុកវិញ។ ជាដំបូង គឺរៀបចំការធ្វើដំណើរត្រលប់ទៅស្រុកវិញ។​ ខ្ញុំបានប្រាប់ឪពុកម្តាយ និងក្រុមគ្រួសារពីថ្ងៃខែ និងពេលវេលានៃការធ្វើដំណើររបស់ខ្ញុំ។ </p>\n <p>អ៊! ម៉ាលីសឯងមានចាំទេ អំពីការជួញដូរមនុស្សដែលអាចកើតមានគ្រប់ពេល និងទីកន្លែង ដូច្នេះខ្ញុំប្រុងប្រយ័ត្នណាស់ក្នុងការធ្វើដំណើរត្រលប់មកវិញ គឺខ្ញុំមិនធ្វើដំណើរជាមួយអ្នកមិនស្គាល់មុខទេ ហើយខ្ញុំធ្វើដំណើរត្រលប់ជាក្រុមជាមួយបងប្អូន សាច់ញាត្តិដែលខ្ញុំទុកចិត្តបំផុត។</p>\n </div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>តើមានរឿងសំខាន់ៗអ្វីខ្លះទៀតដែលយើងត្រូវគិត?</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>រឿងសំខាន់មួយទៀតនោះគឺ ខ្ញុំបានគិតពីមុខរបរ​ និងការងារអ្វីដែលខ្ញុំចង់ធ្វើ​ ឬអាចធ្វើបាន។ ​តើជំនាញអ្វីខ្លះដែលត្រូវការនៅក្នុងសហគមន៍ ឬតំបន់នៅក្បែរស្រុកភូមិរបស់យើង។</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ហើយចុះ ការត្រៀមខ្លួនចូលរស់នៅជាមួយគ្រួសារវិញ កុលាបគិតយ៉ាងមិច?</div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>កុលាប៖</div>\n <div style='flex: 1'>\n <p>បន្ថែមទៀត ខ្ញុំគិត តើខ្ញុំនឹងត្រៀមខ្លួនចូលទៅរស់នៅជាមួយនឹងក្រុមគ្រួសារ និងសហគមន៍យ៉ាងម៉េចដែរ? ព្រោះខ្ញុំបានរស់នៅ និងធ្វើការនៅប្រទេសថៃយូរដែរ។​ ខ្ញុំបានគិតថា តើខ្ញុំធ្វើដូចម្តេច ប្រសិនមានការរើសអើងពីសមាជិកគ្រួសារខ្លះ ឬអ្នកភូមិខ្លះនៅក្នុងសហគមន៍​? តើខ្ញុំអាចភ្ជាប់ខ្លួនយើងទៅនឹងបណ្តាញគំាទ្រដែលមាននៅក្នុងសហគមន៍យ៉ាងម៉េច?ដើម្បីទទួលបានព័ត៌មានអំពីការងារ និងការគាំពារផ្នែកសង្គមផ្សេងៗ រួមទាំងសេវាអំពើហិង្សាលើស្រ្តីផងដែរ។</p>\n <p>លើសពីនេះទៀត​ ខ្ញុំក៏បានចែករំលែកបទពិសោធនៃការទៅធ្វើការនៅប្រទេសថៃជាមួយបងប្អូន និងអ្នកភូមិផ្សេងទៀតដែរ។ ព័ត៌មានពិត ត្រឹមត្រូវពីចំណាកស្រុក គឺជួយឲ្យយើងមានការរៀបចំសម្រាប់ការធ្វើចំណាកស្រុក។​</p>\n </div>\n </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ចុះអារម្មណ៍វិញយ៉ាងម៉េចដែរ?</div>\n  </div>\n <div style='display: flex; flex-direction: row'>\n <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ពេលខ្លះខ្ញុំក៏នឹកពេលវេលា ការចងចាំល្អៗមួយចំនួនផងដែរ។ ជាពិសេសមិត្តរួមការងារជិតស្និតពីរបីនាក់​ តែខ្ញុំមិនសោកស្តាយចំពោះការសម្រេចចិត្តរបស់ខ្ញុំទេ។</div>\n </div>\n </div>",
    "image_url": "/uploads/categories/departure/image/15/coming_home_make_your_plan.png",
    "audio_url": "/uploads/categories/departure/audio/15/c1_3_1_coming_home_prepare_plan.mp3",
    "parent_id": 14,
    "uuid": "de_003_1",
    "leaf": true,
    "lft": 28,
    "rgt": 29,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_make_your_plan.png'),
    "audio": "c1_3_1_coming_home_prepare_plan.mp3",
    "offline": true
  },
  {
    "id": 16,
    "name": "ត្រលប់ចូលក្នុងគ្រួសារ",
    "description": "<div>ការត្រលប់មករស់នៅជាមួយគ្រួសារវិញមានទាំងអារម្មណ៍រំភើប និងការបន្សាំខ្លួនចូលទៅក្នុងរបៀបរស់នៅរបស់គ្រួសារអ្នកវិញ។ ជាការចាំបាច់ដែលអ្នកនិយាយប្រាប់ទៅគ្រួសារ រួមមានឳពុកម្តាយ បងប្អូនស្រី ឬមិត្តភក្តិជិតស្និទ្ធរបស់អ្នកពីអារម្មណ៍របស់អ្នក អ្វីដែលអ្នកចង់ធ្វើ និងពីរបៀបរស់នៅប្រចាំថ្ងៃបែបថ្មីរបស់អ្នក។</div>",
    "image_url": "/uploads/categories/departure/image/16/coming_home_women_migrant_worker.png",
    "audio_url": "/uploads/categories/departure/audio/16/c1_3_2_coming_home_back_home.mp3",
    "parent_id": 14,
    "uuid": "de_003_2",
    "leaf": true,
    "lft": 30,
    "rgt": 31,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker.png'),
    "audio": "c1_3_2_coming_home_back_home.mp3",
    "offline": true
  },
  {
    "id": 17,
    "name": "ស្រ្តីពលករចំណាកស្រុក និងចូលរួមចំណែកក្នុងសេដ្ឋកិច្ច",
    "description": "<div>\n<p>ការធ្វើទេសន្តរប្រវេសន៍ អាចផ្តល់នូវប្រយោជន៍សម្រាប់គ្រប់តួអង្គពាក់ព័ន្ធទាំងអស់។ ពលករទេសន្តរប្រវេសន៍ជាស្រ្តី រួមភាគទានផ្នែកសង្គម និងសេដ្ឋកិច្ចយ៉ាងសំខាន់ ដល់សហគមន៍របស់ពួកគេ ក៏ដូចជាដល់ប្រទេសប្រភពដើម និងប្រទេសគោលដៅ។ ស្រ្តីដែលធ្វើទេសន្តរប្រវេសន៍អាចទទួលបានការងារដែលផ្តល់នូវប្រាក់កម្រៃខ្ពស់ ហើយក្នុងពេលជាមួយគ្នា អាចបង្កើនភាពជាតំណាងរបស់ពួកគេ ក៏ដូចជាធ្វើឱ្យស្ថានភាព ក្នុងគ្រួសារ និងសហគមន៍ របស់ពួកគេកាន់តែមានភាពល្អប្រសើរជាងមុន។ ដូច្នេះ ទេសន្តរប្រវេសន៍ការងាររបស់ស្រ្តី អាចជាប្រភពដ៏សំខាន់ សម្រាប់ផ្តល់ភាពអង់អាចដល់ស្រ្តី។ មានការប៉ាន់ប្រមាណថា នៅក្នុងឆ្នាំ ២០១៦ ប្រាក់ដែលបញ្ជូនដោយពលករទេសន្តរប្រវេសន៍មកប្រទេសកំណើតរបស់ពួកគេមានចំនួន ៦៣,៩ ពាន់លានដុល្លារ។ ប្រហែលជាពាក់កណ្តាលនៃប្រាក់នេះត្រូវបានបញ្ជូនត្រលប់ដោយស្រ្តី។</p>\n<p>ទោះជាយ៉ាងណាក៏ដោយ នៅក្នុងវដ្តនៃការធ្វើទេសន្តរប្រវេសន៍ ពលករទេសន្តរប្រវេសន៍ជាស្រ្តី ប្រឈមនឹងអំពើហិង្សា ការជួញដូរមនុស្ស និងការរើសអើង ដែលរឹតត្បិតលទ្ធភាពរបស់ពួកគេ មិនឱ្យទទួលបានការជ្រើសរើសធ្វើជាពលករដោយយុត្តិធម៌ និងការងារសមរម្យ។ ពួកគេក៏មានឱកាសតិចតួច ក្នុងការទទួលបានសេវាការពារ និងគាំទ្រផងដែរ។</p>\n</div>",
    "image_url": "/uploads/categories/departure/image/17/coming_home_women_migrant_worker_and_economic.png",
    "audio_url": "/uploads/categories/departure/audio/17/c1_3_3_coming_home_women_migrant_worker_and_economic.mp3",
    "parent_id": 14,
    "uuid": "de_003_3",
    "leaf": true,
    "lft": 32,
    "rgt": 33,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker_and_economic.png'),
    "audio": "c1_3_3_coming_home_women_migrant_worker_and_economic.mp3",
    "offline": true
  },
  {
    "id": 18,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/18/before_you_go_video.png",
    "audio_url": "/uploads/categories/departure/audio/18/video.mp3",
    "parent_id": null,
    "uuid": "de_004",
    "leaf": true,
    "lft": 35,
    "rgt": 36,
    "type": "Categories::Departure",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/before_you_go_video.png'),
    "audio": "video.mp3",
    "offline": true
  },
  {
    "id": 19,
    "name": "សិទ្ធិ និងសុវត្ថិភាពរបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/safety/image/19/your_safety_safety_planning.png",
    "audio_url": "/uploads/categories/safety/audio/19/c2_1_right_and_your_safety.mp3",
    "parent_id": null,
    "uuid": "sa_001",
    "leaf": false,
    "lft": 37,
    "rgt": 48,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_safety_planning.png'),
    "audio": "c2_1_right_and_your_safety.mp3",
    "offline": true
  },
  {
    "id": 20,
    "name": "អំពើហិង្សាលើស្រ្តី",
    "description": "<div>\n  <ul style='marginLeft: -18;'>\n    <li>អំពីហិង្សាលើស្ត្រី គឺជាទង្វើអំពើហិង្សាដែលទាក់ទងនឹងយេនឌ័រដែលនាំឲ្យមាន ឬទំនងជាបង្កអោយមានគ្រោះថ្នាក់ ឬការឈឺចាប់ផ្លូវកាយ ផ្លូវភេទ ឬផ្លូវចិត្តដល់ស្រ្តីរួមនឹងការគំរាមកំហែងប្រព្រឹត្តទង្វើទំាងនេះ ការបង្ខិតបង្ខំ ការបំបិទសេរីភាពតាមអំពើចិត្តមិនថាកើតមានឡើងនៅទីសាធារណៈ ឬ ជីវិតឯកជននោះទេ។</li>\n    <li>អំពីហិង្សាលើស្ត្រីគ្រប់ទម្រង់ គឺជាការរំលោភសិទ្ធិស្រ្តី។</li>\n  </ul>\n\n  <h2 style='marginBottom: 10;'>ទម្រង់ផ្សេងៗអំពើហិង្សាលើស្រ្តី</h2>\n\n  <div>\n    <div>ហិង្សាផ្លូវកាយ៖</div>\n    <div style='marginLeft: 20;'>វាយដំ ឬដាល់ រុញឲ្យដួល ទះ តប់ គប់ដោយប្រើរបស់ផ្សេងៗ ការខំា ការទាញសក់ ការកាត់ ឬចាក់ ការធ្វើអោយថប់ដង្ហើម និងការដុត ។ល។</div>\n  </div>\n\n  <div style='display: flex;'>\n    <div style='width: 130px;'>ហិង្សាផ្លូវចិត្ត៖</div>\n    <div style='marginLeft: 20;'>\n      <ul style='marginTop: 0; marginLeft: -18;'>\n        <li>ជេរ​ប្រមាថ​ មើល​ងាយ​ ឬ​សម្លុត​គំរាម​កំហែង</li>\n        <li>មិន​គោរព​ ផ្តល់​តម្លៃ​ និង​ទំនុក​ចិត្ត</li>\n        <li>និយាយ​ចំអក​បញ្ឈឺ​ចិត្ត​ និង​ធ្វើ​អោយ​អាម៉ាសមុខ</li>\n        <li>ការ​បដិសេដ​លើ​គំនិត​ និង​យោបល់</li>\n        <li>គ្រប់​គ្រង​ និង​បំបិត​សិទ្ធ​សេរីភាព</li>\n        <li>បដិសេធមិនគោរពនូវជំនឿ</li>\n        <li>ការរំពឹងចង់បានច្រើនហួសហេតុ</li>\n        <li>ចេះតែរិះគន់ឥតឈប់ឈរ</li>\n        <li>ទាម​ទារ​អ្វីៗ​ដោយ​មិន​សម​ហេតុផល</li>\n        <li>និយាយ​ចោទ​ប្រកាន់​ ស្តី​បន្ទោស​ គំរាម​ ឬ​បង្គាប់​បញ្ជា</li>\n      </ul>\n    </div>\n  </div>\n\n  <div style='display: flex; marginTop: -20'>\n    <div style='width: 130px;'>ហិង្សាផ្លូវភេទ៖</div>\n    <div style='marginLeft: 20;'>ការរំលោភសេពសន្ថវៈ, ការរំលោភសេពសន្ថវៈក្នុងចំណងអាពាហ៍ពិពាហ៍, ស្មន្ធការ (ការរួមភេទជាមួយសាច់ញាតិខ្លួនឯង), បៀតបៀនផ្លូវភេទ, រុកគួនខាងផ្លូវភេទ, បង្ហាញកេរភេទ, ការនិយាយទាក់ទងផ្លូវភេទដែលមិនសមរម្យ ឬសំដែងឥរិយាបទផ្លូវភេទដែលធ្វើឲ្យមានការភ័យខ្លាច, ការប៉ះពាល់រាងកាយ ឬកេរិ៍្តភេទដោយចេតនា, ការបង្ខំឲ្យធ្វើសកម្មភាពផ្លូវភេទ ដូចជាបង្ខំឲ្យរួមភេទតាមមាត់, មើលរឿងអាសអាភាស, ផលិតសម្ភារៈ ឬឧបករណ៍អាសអាភាស ឬមើលសកម្មភាពរួមភេទ ឬលើកទឹកចិត្តអោយប្រព្រឹត្តអាកប្បកិរិយាទាក់ទងនឹងផ្លូវភេទមិនសមរម្យ។ល។</div>\n  </div>\n\n  <div style='display: flex;'>\n    <div style='width: 130px;'>ហិង្សាផ្នែកសេដ្ឋកិច្ច៖</div>\n    <div style='marginLeft: 20;'>មិនអនុញ្ញាតឱ្យទទួលបានអាហារ ប្រាក់កាស សម្លៀកបំពាក់ ថ្នាំសង្កូវ ការអប់រំ មិនអនុញ្ញាតឱ្យទៅធ្វើការងារ បង្ខំឱ្យធ្វើការងារ ដកហូតប្រាក់ចំនូលទាំងអស់ ពុំផ្តល់សិទ្ធិកាន់កាប់ទ្រព្យសម្បត្តិ</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row; marginTop: 30'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំ​បាន​ឮ​ថា​បង​ប្អូន​ស្រ្តី​ពលករ​ចំណាក​ស្រុក​ជួប​នូវ​បទពិសោធ​អំពើ​ហិង្សា​ តើ​កុលាប​មាន​ដែល​ឭ​ ឬ​ឃើញ​អំពី​ហិង្សា​លើ​ស្រ្តី​ទេ?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>កុលាប៖</div><div style='flex: 1'>ខ្ញុំ​បាន​ដឹង​រឿង​មិត្ត​រួម​ការ​ងារ​ជិត​ស្និត​ម្នាក់​ គឺ​រស្មី។​ រស្មី​គាត់​រៀប​ការ​ប្រមាណ​ជាង​៣ឆ្នាំ​ហើយ​ ​ជា​មួយ​នឹង​ប្តី​ របស់​គាត់ឈ្មោះ​វិច្ឆិកា​ ដែល​ធ្វើ​ការ​នៅ​ថៃ​ទាំង​ពីរ​នាក់។​ រស្មី​ប្រាប់​ខ្ញុំ​ថា​ មុន​រៀប​ការ​ វិច្ឆិកា​ គឺ​ប្រច័ណ្ឌ​ខ្លាំង​ណាស់។​ តែ​ពេល​ណុង៎​ រស្មី​គិត​ថា​ដោយ​សារ​តែ​គាត់​ស្រលាញ់​នាង​ខ្លាំង​ពេក។​ ដល់​ពេល​រៀប​ការ​ហើយ​ ប្តី​របស់​រស្មី​ គឺ​មិន​ចង់​ឲ្យ​គាត់​រាប់​អាន​មិត្ត​ភក្តិ​ ឬ​ធ្វើ​ការ​កន្លែង​បែក​ពី​គ្នា​ទេ។​ ប៉ុន្តែ​ប្តី​របស់​រស្មី​វិញ​ ឲ្យ​តែ​បើក​ប្រាក់​ខែ​ម្តងៗ​ ដឹង​តែ​ដើរ​លេង​ជា​មួយ​និង​គូរ​កន​របស់​គេ​ដាច់​យប់​រហូត។​ រស្មី​បាន​ប្រាប់ខ្ញុំ​ទៀត​ថា​ ពេល​មួយ​នោះ​ ក្រោយ​ពី​បើក​ប្រាក់​ខែ​ហើយ​ ប្តី​គេ​ដើរ​សប្បាយ​ដល់​យប់​ជ្រៅ​ ស្រាប់​តែ​មក​ដល់​ផ្ទះ​រក​រឿង​ ថា​រស្មី​មាន​ប្រុស​អី​ណា​ ដោយ​គ្មាន​ហេតុ​ផល​អីសោះ​ ដល់​ពេល​នាង​ប្រកែក​ ប្តី​នាង​បាន​ទះ​កំផ្លៀង​ និង​រុញ​ឲ្យ​ដួល។​​ ក្រោយ​មក​ វិច្ឆិកា​បាន​មក​សុំ​ទោស​ដែល​បាន​ជ្រុល​ដៃ​ទះ​កំផ្លៀង​ប្រពន្ធ​ និង​សន្យា​មិន​ធ្វើ​អញ្ចឹង​ទៀត​ទេ។​ មិន​បាន​ប្រហែល​មួយ​អាទិត្យ​ផង​ ប្តី​រស្មី​បាន​ធ្វើ​ទង្វើ​នេះ​ដដែល​ ហើយ​កាន់​តែ​អាក្រក់​ជាង​មុន​ទៅ​ទៀត​ គឺ​បាន​ដាល់​មុខ​រស្មី​មួយ​ដៃ​យ៉ាង​ធ្ងន់។​</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px;'>ម៉ាលីស៖</div><div style='flex: 1'>ដល់​ថ្នាក់​ហ្នឹង​ផង!​ វិច្ឆិកានោះ​ពិត​ជា​អាក្រក់​មែន​ គេ​គួរ​តែ​ត្រូវ​បាន​ទទួល​ទោស​ចំពោះ​ទង្វើ​ហិង្សា​ដែល​គេ​បាន​ប្រព្រឹត្តិ​មក​លើ​រស្មី។​ តែ​ជា​ការ​ល្អ​ណាស់​ ដែល​រស្មី​មាន​មិត្ត​ល្អ​ដូច​កុលាប​ឯង​ ព្រោះ​នាង​មាន​ មិត្ត​ល្អ​ដែល​អាច​ទុក​ចិត្ត​និយាយ​រឿង​រ៉ាវ​ក្នុង​ចិត្ត​ប្រាប់​បាន។​</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/safety/image/20/violence_on_women.png",
    "audio_url": "/uploads/categories/safety/audio/20/c2_1_1_violence_on_women.mp3",
    "parent_id": 19,
    "uuid": "sa_001_1",
    "leaf": true,
    "lft": 38,
    "rgt": 39,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/violence_on_women.png'),
    "audio": "c2_1_1_violence_on_women.mp3",
    "offline": true
  },
  {
    "id": 21,
    "name": "ការបៀតបៀនផ្លូវភេទ",
    "description": "<div>\n  <div>ការបៀតបៀនផ្លូវភេទ គឺជាទង្វើ ឬឥរិយាបថទាំងឡាយណាដែលមិនចង់បាន មិនស្វាគមន៍ ឬក៏មិនអនុញ្ញាតពាក់ព័ន្ធនឹងផ្លូវភេទដែលធ្វើអោយបុគ្គលម្នាក់ ឬច្រើននាក់មានអារម្មណ៍អាម៉ាស់មុខ ភិតភ័យ ឬអាក់អន់ចិត្ដ។ ការបៀតបៀនផ្លូវភេទមានទម្រង់ខុសគ្នារួមមាន៖ ការបៀតបៀនផ្លូវភេទដោយប្រើអំណាច ពាក្យសម្ដី សំលេង និងការបៀតបៀនផ្លូវភេទដោយកាយវិការ ។</div>\n  <div style='color: red; margin-top: 10px'>ឧទាហរណ៍ ការបៀតបៀនផ្លូវភេទដោយពាក្យសម្ដី</div>\n  <ul>\n    <li>ការ​ប្រើ​ប្រាស់​ភាសា​មិន​សមរម្យ​ ឬ​ភាសា​អាសអាភាស​ និង​និយាយ​លេង​សើច​បែប​អាសអាភាស</li>\n    <li>ការ​ហៅ​មិន​សមរម្យ​ទៅ​កាន់​ស្រ្ដី​នៅ​តាម​ផ្លូវ​ ឬ​ការ​ប្រើ​ភាសា​អាសអាភាស​នៅ​ពេល​ស្រ្តី​ដើរ​កាត់</li>\n    <li>ការ​ហូច​បែប​មិន​សមរម្យ​នៅ​ពេល​ស្រ្តី​ដើរ​កាត់</li>\n    <li>សំណើរ​ និង​ការ​លួង​លោម​ដដែលៗ​ ដើម្បី​បំពេញ​ចំណង់​ផ្លូវ​ភេទ​ ឬ​ការ​ណាត់​ជួប​ក្នុង​គោល​បំណង​ផ្លូវ​ភេទ</li>\n    <li>ការ​និយាយ​សម្តី​ដែល​មាន​លក្ខណៈ​ផ្លូវ​ភេទ​ (ឧទាហរណ៍៖​ ហៅឈ្មោះ​ជា​លក្ខណៈ​ផ្លូវ​ភេទ​ ឬ​សួរ​អំពី​អត្ត​សញ្ញាណ​ផ្លូវ​ភេទ​ ឬ​ការ​ប្រព្រឹត្ត​ខាង​ផ្លូវ​ភេទ)</li>\n    <li>ការវាយប្រហារឯកជនភាព ទាំងក្នុង និងក្រៅសាលារៀន ឬកន្លែងធ្វើការ (ឧទាហរណ៍៖ការបៀតបៀន ដោយការហៅទៅទូរស័ព្ទ ឬដើរតាមស្រ្ដីនោះដល់ផ្ទះ)</li>\n    <li>ការ​ស្នើ​ដាក់លក្ខខណ្ឌ​ដោះ​ដូរ​ដើម្បី​បំពេញ​ចំណង់​ផ្លូវ​ភេទ​ផ្ទាល់​ខ្លួន​ ដូច​ជា​ ការ​ផ្ទេរ​ ការ​ដំឡើង​ឋានៈ​ ប្រាក់​ខែ​ ឬ​បន្ដ​ការងារ</li>\n    <li>គំរាម​កំហែង​វាយ​ធ្វើ​បាប​ បង្ខិត​បង្ខំ​ ឬ​រំលោភ​ផ្លូវ​ភេទ។</li>\n  </ul>\n\n  <div style='color: red;'>ឧទាហរណ៍ ការបៀតបៀនផ្លូវភេទដោយកាយវិការ</div>\n  <ul>\n    <li>ការ​តាំង​បង្ហាញ​វត្ថុ​ដែល​ធ្វើ​ឱ្យ​នឹក​ឃើញ​ដល់​ផ្លូវ​ភេទ​ ដូច​ជា​រូបភាព​ ទស្សនាវដ្ដី​ ផ្ទាំង​រូបភាព​ ឬ​តុក្កតា​អាសអាភាស</li>\n    <li>ការ​សម្លក់​សម្លឹង​ ឬ​សញ្ញា​កាយ​វិការ​ដែល​ទាក់​ទង​នឹង​ផ្លូវ​ភេទ</li>\n    <li>ការ​ប៉ះ​ ការ​ថើប​ ការ​ឱប​ក្រសោប​ ការ​ធ្វើ​សរសៃ​ ឬ​ការ​អង្អែល​លើ​រាង​កាយ​ដែល​មិន​អនុញាត</li>\n    <li>ការ​វាយ​ធ្វើ​បាប​ ឬ​បង្ខិត​បង្ខំ​ និង​រំលោភ​ផ្លូវ​ភេទ </li>\n  </ul>\n  <div>ទោះបីជានរណាក៏អាចជាកម្មវត្ថុនៃអំពើបៀតបៀនផ្លូវភេទ ស្រ្តីភាគច្រើនត្រូវបានក្លាយជាជនរងគ្រោះនៃការបៀតបៀនផ្លូវភេទ។ ទម្រង់នៃការការបៀតបៀនផ្លូវភេទ គឺអាចកើតមាននៅគ្រប់ទីកន្លែងទាំងអស់ រួមទាំងកន្លែងធ្វើការ។ នៅកន្លែងធ្វើការ ការបៀតបៀនផ្លូវភេទពេលខ្លះ គឺជាទង្វើមួយដែលជម្រុញឲ្យទទួលយកជាថ្នូរ និងផលប្រយោជន៍ត្រលប់មកវិញ។ ជាក់ស្តែង ការស្នើដាក់លក្ខខណ្ឌដោះដូរដើម្បីបំពេញចំណង់ផ្លូវភេទផ្ទាល់ខ្លួន ដូចជា ការផ្ទេរ ការដំឡើងឋានៈ ប្រាក់ខែ ឬបន្ដការងារ។</div>\n</div>",
    "image_url": "/uploads/categories/safety/image/21/harassment.png",
    "audio_url": "/uploads/categories/safety/audio/21/c2_1_2_harassment.mp3",
    "parent_id": 19,
    "uuid": "sa_001_2",
    "leaf": true,
    "lft": 40,
    "rgt": 41,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/harassment.png'),
    "audio": "c2_1_2_harassment.mp3",
    "offline": true
  },
  {
    "id": 22,
    "name": "សុខភាពរបស់អ្នក",
    "description": "<div>\n  <div>ការ​ថែទាំ​សុខភាព​របស់​អ្នក​ គឺ​មាន​សារៈ​សំខាន់​ណាស់​ ទន្ទឹម​នឹង​ពេល​ដែល​អ្នក​ខ្វល់​ខ្វាយ​ និង​រវល់​ជា​មួយ​ការងារ​ប្រចាំ​ថ្ងៃ។ </div>\n\n  <ul>\n    <li>មិន​មែន​ជា​ការ​ខ្មាស់​អៀន​នោះ​ទេ​ក្នុង​ការ​និយាយ​អំពី​បទពិសោធន៍​ ឬ​ចំងល់​ផ្សេងៗ​ទាក់ទង​នឹង​ការ​មក​រដូវ​របស់​អ្នក។​ មិត្ត​ភក្តិ​ជិត​ស្និទ្ធ​ ឬ​បង​ប្អូន​ស្រី​ ឬ​ម្តាយ​អាច​ជា​មនុស្ស​ដែល​គួរ​ឲ្យ​ទុក​ចិត្ត​ និង​មាន​អារម្មណ៍​សុវត្ថិភាព​សម្រាប់​អ្នក​ក្នុង​ការ​និយាយ​ប្រាប់​អំពី​កង្វល់​ ឬ​ការ​ព្រួយ​បារម្ភ​ផ្សេងៗ​អំពី​ការ​មក​រដូវ​របស់​អ្នក។</li>\n    <li>ជាធម្មតា ស្រ្តីមករដូវជារៀងរាល់ចន្លោះពី ២៨ ទៅ ៤០ ថ្ងៃ ដែលជាវដ្តទូទៅ ហើយជារឿងធម្មតា។ រដូវ ទៀង គឺមានន័យថាមកជារៀងរាល់ ២៨ ថ្ងៃម្តង។ ប៉ុន្តែជាករណីកម្រដែលស្រ្តីមករដូវទៀងក្នុងកំឡុងពេល ២៨ថ្ងៃ។ ស្រ្តីខ្លះអាចមករដូវក្នុងកំឡុងពេល ៣០ ថ្ងៃ អ្នកខ្លះ ៣១ ថ្ងៃ ឬអ្នកខ្លះ ៣៥ ថ្ងៃ លើសពីនេះទៀតមានអ្នកខ្លះរហូតដល់ ៤០ ថ្ងៃ។</li>\n    <li>យុវតី​ និង​ស្រ្តី​មាន​ការ​ព្រួយ​បារម្ភ​ពី​ការ​ធ្លាក់ស​របស់​ពួក​គេ។​ ជា​ធម្មតា​ ស្រ្តី​មាន​ការ​ធ្លាក់ស​មុន​មក​រដូវ​ និង​ក្រោយ​មក​រដូវ។​ នេះ​ជា​រឿង​ធម្មតា​ទេ។​ ប៉ុន្តែ​ ប្រសិន​បើ​ការ​ធ្លាក់ស​ របស់​អ្នក​មាន​ធុំ​ក្លិន​ មាន​ពណ៌​ដូច​ជា​សំបោរ​ពណ៌​លឿង​ អ្នក​គួរ​តែ​រក​ការ​ពិគ្រោះ​យោបល់​ជា​មួយ​គ្រូពេទ្យ​ខាង​ផ្នែក​រោគ​ស្រ្តី។ </li>\n    <li>អនាម័យ​នៅ​ពេល​មាន​រដូវ​ ដូច​ជា​​ការ​​លាង​​សម្អាត​​ឲ្យ​​បាន​​ញឹក​ញាប់​​ ការ​​ប្តូរ​​សំឡី​​អនាម័យ​​ ឬ​​ក្រណាត់​ទ្រាប់​ ជា​រៀង​រាល់​ ៣ ទៅ​ ៤ ម៉ោង​ ការ​ហូប​អាហារ​មាន​បន្លែ​ ផ្លែ​ឈើ​ និង​ហូប​ទឹក​ឲ្យ​បាន​ច្រើន​ សម្រាក​ឲ្យ​បាន​គ្រប់​គ្រាន់​ គឺ​ជួយ​នាំ​មក​នូវ​សុខ​ភាព​បន្ត​ពូជ​ល្អ​ និង​រឹងមាំ។</li>\n    <li>ការ​ស្វែង​រក​ការ​ពិគ្រោះ​យោបល់​ជា​មួយ​គ្រូពេទ្យ​ខាង​ផ្នែក​រោគ​ស្រ្តី​ គឺ​មាន​សារៈ​សំខាន់​ណាស់។​ កុំ​ភ្លេច​ណា៎​ ការ​និយាយ​ពី​ការ​មក​រដូវ​ ឬ​សុខភាព​បន្ត​ពូជ​ មិន​មែន​ជា​រឿង​ខ្មាស់​អៀន​ទេ!!!</li>\n    <li>អ្នក​ គឺ​ជា​ម្ចាស់​លើ​រាង​កាយ​របស់​អ្នក។​ អ្នក​មាន​សិទ្ធិ​ធ្វើ​សេចក្តី​សម្រេច​ចិត្ត​លើ​ផែនការ​ពន្យារ​កំណើត​ និង​ការ​កំណត់​ចំនួន​កូន​ដែល​អ្នក​ចង់​បាន។​ មាន​ជម្រើស​ជា​ច្រើន​ ដូច​ជា​ ការ​ប្រើ​ប្រាស់​ស្រោម​អនាម័យ​ ថ្នាំ​ចាក់​ ថ្នាំ​គ្រាប់​ កង​ដាក់​ក្រោម​ស្បែក​ និង​កង​ដាក់​ក្នុង​ស្បូន​ ដែល​ជា​សេវា​សុខភាព​សាធារណៈ​ ហើយ​អាច​រក​សេវា​នេះ​បាន​ ដូច​ជា​ មណ្ឌល​សុខភាព​ ឬ​មន្ទីរពេទ្យ​បង្អែក​ជាដើម​ ដែល​ជា​មធ្យោបាយ​មាន​ប្រសិទ្ធិភាព​ខ្ពស់​សម្រាប់​ការ​ពន្យា​កំណើត។​ មធ្យោបាយ​ពន្យា​កំណើត​បែប​ធម្មជាតិ​ ដូច​ជា​តាម​រយៈ​ការ​បំបៅ​ដោះ​កូន​ តាម​រយៈ​ប្រតិទិន​ តាម​រយៈ​ការ​ដក​ទឹកកាម​ចេញ។​ ប្រសិទ្ធភាព​របស់​វា​ គឺ​មិន​មានខ្ពស់ទេ ហើយ​ប្រឈម​នឹង​មាន​ផ្ទៃ​ពោះ​ដោយ​មិន​ចង់​បាន​ ឬ​ចៃដន្យ។ </li>\n  </ul>\n\n  <div>កុំ​ភ្លេច​ ពិគ្រោះ​យោបល់​ជា​មួយ​គ្រូពេទ្យ​ជំនាញ​ នៅ​ពេល​អ្នក​ចង់​ធ្វើ​ផែនការ​ពន្យា​កំណើត។​ ស្វែង​យល់​ពី​ផល​ប៉ះពាល់​ និង​ប្រសិទ្ធិភាព​នៃ​មធ្យោបាយ​ពន្យារ​កំណើត​និមួយៗ​ ជា​ការ​ចាំបាច់!</div><div>រាងកាយខ្ញុំ ជម្រើសខ្ញុំ​​ !!!</div>\n</div>",
    "image_url": "/uploads/categories/safety/image/22/your_health.png",
    "audio_url": "/uploads/categories/safety/audio/22/c2_1_3_your_health.mp3",
    "parent_id": 19,
    "uuid": "sa_001_3",
    "leaf": true,
    "lft": 42,
    "rgt": 43,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_health.png'),
    "audio": "c2_1_3_your_health.mp3",
    "offline": true
  },
  {
    "id": 23,
    "name": "ស្វែងយល់អំពីការកេងប្រវ័ញ្ច និងការជួញដូរ",
    "description": "<div>\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div><div style='flex: 1'>ខ្ញុំ​បាន​ឮ​អ្នក​ភូមិ​ មេក្រុម​ មេភូមិ​ និយាយ​អី​ទេ​ថា​បង​ប្អូន​ស្រ្តី​ពលករ​ចំណាក​ស្រុក​ប្រយ័ត្ន​ត្រូវ​គេ​ជួញដូរ។​ តើ​យ៉ាង​ម៉េច​វិញ​ កុលាប?​ ក្រែង​យើង​ទៅ​ធ្វើ​ការ​ ចុះ​ហេតុអី្វ​បាន​ជា​ គេ​អាច​ជួញ​ដូរ​ ឬ​កេង​ប្រវ័ញ្ច​យើង​បាន​យ៉ាង​ម៉េច​វិញ?​</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>ខ្ញុំធ្លាប់បានចូលរួមវគ្គបណ្តុះបណ្តាលទាក់ទងអំពីជួញដូរមនុស្ស និងការកេងប្រវ័ញ្ច ខ្ញុំអាចប្រាប់ម៉ាលីសបានណា។\n      <p>ការជួញដូរមនុស្ស គឺជាការជ្រើសរើស ការដឹកជញ្ជូន ការផ្ទេរ ការឃាត់ទុក ឬការផ្តល់ទីជម្រក តាមមធ្យោបាយគំរាមគំហែង ការប្រើកម្លាំង ទម្រង់ផ្សេងទៀតនៃការបង្ខិតបង្ខំ ការចាប់ ពង្រត់ ការក្លែងបន្លំឯកសារ ការបោកប្រាស់ ការរំលោភបំពានអំណាច ការប្រើតួនាទីរំលោភជនរងគ្រោះ ការឲ្យ ឬទទួលយកកម្រៃ ឬអត្ថប្រយោជន៍ណាមួយដើម្បីសម្រេចបានការព្រមព្រៀងឲ្យមានការត្រួតត្រាលើមនុស្សម្នាក់ទៀត។</p>\n    </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div>\n    <div style='flex: 1'>អូ ឈប់ៗ​កេង​ប្រវ័ញ្ច​​ កេងប្រវ័ញ្ច​យ៉ាង​ម៉េច​ទៅ?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div><div style='flex: 1'>ការ​កេងប្រវ័ញ្ច​រួម​មាន​ ការកេងប្រវ័ញ្ច​លើពេស្យាកម្ម​ជនដទៃ​ ឬទម្រង់​ផ្សេងៗ​ទៀត​នៃ​ការ​កេងប្រវ័ញ្ច​ផ្លូវ​ភេទ​ ពលកម្ម​ ឬ​សេវា​ដោយ​បង្ខំ​ ទាសភាព​ ឬ​ការ​អនុវត្តន៍​ស្រដៀង​គ្នា​នឹង​ទាសភាព​ ទាសករ​ ឬ​ការដក​ហូត​សរីរាង្គ​ណាមួយ។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div>\n    <div style='flex: 1'>ស្ដាប់​ទៅ​ ខ្ញុំ​ដូចជា​នៅ​មិន​ទាន់​យល់​បាន​ច្បាស់​ តើ​កុលាប​អាច​ឧទាហរណ៍​អ្វី​បន្ថែម​ទៀត​មើល។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>ខ្ញុំ​មាន​រឿង​មួយដែល​ខ្ញុំ​បាន​ដឹង​ពី​អ្នក​ធ្វើការ​ជាមួយ​គ្នា​ កាល​នៅ​ប្រទេស​ថៃ។ មាន​ស្ត្រី​ម្នាក់​ឈ្មោះ​ចិន្ដា​ គាត់​បាន​ដឹង​តាមរយៈ​បុរស​ម្នាក់​នៅក្នុង​ភូមិ​ ថា​នៅ​ប្រទេស​ថៃ​មាន​ឱកាស​ច្រើន​នឹង​អាច​រក​ការងារ​ធ្វើ​បាន។​ បុរស​នោះ​ជា​មេខ្យល់​នាំ​មនុស្ស​ទៅ​ធ្វើការ​នៅ​រោងចក្រ​នៅ​ប្រទេស​ថៃ។ ហើយ​បាន​ប្រាប់​ចិន្ដា​ថា​ ការចំណាក​ស្រុក​អស់​លុយ​តិច​តួច​ទេ​ ព្រម​ទាំង​មិន​ចាំបាច់​ចំណាយ​លើ​ថ្លៃ​ធ្វើ​ឯកសារ​ ក៏​អាច​ទៅ​ធ្វើការ​បាន​ដូច​គ្នា។\n    បុរស​នោះ​ប្រាប់​ចិន្ដា​ កុំ​ឲ្យ​មាន​ការ​បារម្ភ​អ្វី​ទាំងអស់​ គាត់​ធានា​ថា​គ្រប់​យ៉ាង​នឹង​គ្មាន​បញ្ហា​ ចិន្ដា​នឹង​បាន​ការងារ​ធ្វើ​នៅ​ប្រទេស​ថៃ​ ហើយ​មាន​ប្រាក់​ខែ​ខ្ពស់។ លឺសំដីបុរសនោះ ធានា​បែប​នេះ​ ចិន្តា​ក៏​ជឿជាក់។ បុរស​នោះ​តម្រូវ​ឲ្យ​ចិន្ដា​បង់​លុយ​មួយ​ចំនួន​ ដើម្បី​ធ្វើ​ដំណើរ​ទៅ​ធ្វើការ​នៅ​ប្រទេស​ថៃ។ ម៉ាលីស​ដឹងអត់​ ថា​ចិន្ដា​ធ្វើ​ដំណើរ​បែប​ណា​ដើម្បី​ចូល​ទៅ​ប្រទេស​ថៃ?\n    </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div>\n    <div style='flex: 1'>ប្រាប់​មក​កុលាប​ ថា​ចិន្ដា​ទៅ​ដោយ​របៀបណា?</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>ចិន្ដា​ត្រូវ​លាក់​ខ្លួូន​នៅ​ក្នុង​ឡាន​ដឹក​ទំនិញ​ដើម្បី​ឆ្លង​ដែន។ ពេល​គាត់​ទៅ​ដល់​ស្រាប់​តែ​គេ​ប្រាប់​ថា​ រោងចក្រ​មិន​ទាន់​បើក​ឲ្យ​ដំណើរការ​នោះ​ទេ។ ប៉ុន្តែ​ចិន្ដា​អាច​ធ្វើ​ការ​នៅ​បារ​មួយ​កន្លែង​នៅ​ទី​ក្រុង​ដ៏ធំ​នោះ។ ម្ចាស់​បារ​បាន​ផ្ដល់​កន្លែង​ស្នាក់នៅ​ឲ្យ​ចិន្ដា​ និងបាន​ដក​លិខិត​ឆ្លង​ដែន​របស់​នាង​ទុក។ ហើយ​ក៏​មិន​ឲ្យ​ចិន្ដា​ប្រើ​ប្រាស់​ទូរស័ព្ទ​បាន​ដែរ។ 2-3ថ្ងៃ​ក្រោយ​មក​ ចិន្ដា​ក៏​បាន​ដឹង​ថា​ នារី​ទាំងអស់​នៅ​ទីនោះ​ គឺ​ត្រូវ​រួម​ភេទ​ជា​មួយ​ភ្ញៀវ​\n    ដើម្បី​បាន​លុយ​ ហើយ​នាង​ត្រូវ​បាន​គេ​បង្ខំ​ឲ្យ​ធ្វើ​បែប​នោះ​ដូច​គ្នា​ដែរ។\n    </div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div>\n    <div style='flex: 1'>ចុះ​សាច់រឿង​យ៉ាង​ម៉េច​ទៀត​ ចិន្ដា​ធ្វើ​យ៉ាងម៉េច​ទៅ? ខ្ញុំ​ស្ដាប់​ហើយ​បារម្ភ​ពី​ចិន្ដា​ណាស់។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>ចិន្ដា​បាន​ព្យាយាម​រត់​ចេញ​ពី​ទី​នោះ​ ប៉ុន្តែ​នាង​ត្រូវ​បាន​គេ​បង្ខាំ​មិន​ឲ្យ​ចេញ​ទៅ​ណា​បាន​ទេ​ ហើយ​ម្ចាស់​បារ​នោះ​ បាន​ប្រាប់​ចិន្ដា​ថា​ នាង​បាន​ជំពាក់​លុយ​គេ​ច្រើន​ណាស់​ លើការ​ចំណាយ​ឲ្យ​នាង​បាន​មក​ដល់​ទី​នេះ​ អញ្ចឹង​ហើយ​នាង​ត្រូវ​តែ​ធ្វើការ​ដើម្បី​ដោះ​បំណុល​ទាំងអស់​នោះ។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>ម៉ាលីស៖</div>\n    <div style='flex: 1'>ពិត​ជា​អាក្រក់​មែន​ បោកបញ្ឆោត​ ភូតកុហក​ បង្ខំ​ឲ្យ​ចិន្ដា​ធ្វើ​ការ​ដែល​នាង​មិន​ចង់​ធ្វើ​ ហើយ​ថា​នាង​ជា​កូន​បំណុល​ទៀត​ទាំង​ដែល​ចិន្ដា​មិន​ធ្លាប់​បាន​ខ្ចី​លុយ​ថៅកែ​នោះ​ផង។ ចំណែកឯ​ បុរស​ដែល​សន្យា​រក​ការងារ​ឲ្យ​ចិន្ដា​ធ្វើ​ និងថា​បាន​ប្រាក់​ខែ​ច្រើន​នោះ​វិញ​ ពិត​ជា​សំបូរ​ល្បិច​គេចកល​បោកបញ្ឆោត​ ដើម្បី​ឲ្យ​ចិន្ដា​មាន​ការ​ជឿជាក់​ បាន​ជា​ចិន្ដា​ត្រូវ​បាន​ធ្លាក់​ចូល​អន្ទាក់​នៃ​ការ​កេងប្រវ័ញ្ច​ផ្លូវភេទ​បែបនេះ។</div>\n  </div>\n\n  <div style='display: flex; flex-direction: row'>\n    <div style='width: 90px'>កុលាប៖</div>\n    <div style='flex: 1'>ស្ដាប់​ហើយ​ខឹង​យ៉ាងនេះ​ ប្រហែល​ជា​ម៉ាលីស​ឯង​យល់​ច្បាស់​ហើយ​មើលទៅ!</div>\n  </div>\n</div>",
    "image_url": "/uploads/categories/safety/image/23/understand_exploitation_and_human_traficking.png",
    "audio_url": "/uploads/categories/safety/audio/23/c2_1_4_understand_exploitation_and_human_traficking.mp3",
    "parent_id": 19,
    "uuid": "sa_001_4",
    "leaf": true,
    "lft": 44,
    "rgt": 45,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/understand_exploitation_and_human_traficking.png'),
    "audio": "c2_1_4_understand_exploitation_and_human_traficking.mp3",
    "offline": true
  },
  {
    "id": 24,
    "name": "សិទ្ធិរបស់អ្នក និងកិច្ចគាំពារ",
    "description": "<div>\n<div>ស្វែងយល់ពីសិទ្ធិរបស់អ្នក</div>\n<ul>\n<li>ពលករចំណាកស្រុកជាស្ត្រី ទាំងអ្នកមានឯកសារ និងមិនមានឯកសារ គឺត្រូវបានការពារដោយច្បាប់ជាតិ និងអន្តរជាតិ។ ទោះបីអ្នកមកពីណា ស្ថានភាពនៃការធ្វើចំណាស្រុករបស់អ្នកយ៉ាងណាក៏ដោយ អ្នកមានសិទ្ធិទទួលបាននូវសុវត្ថិភាព។</li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិទទួលបានក្នុងការរក្សាទុកនូវឯកសារផ្ទាល់ខ្លួន ដូចជាអត្តសញ្ញាណប័ណ្ណ លិខិតឆ្លងដែន និងឯកសារពាក់ព័ន្ធផ្សេងៗទៀត។ មនុស្សគ្រប់រូបត្រូវតែទទួលបាន ការផ្តល់សេវាសាធារណៈ។ ឧទាហរណ៍ សេវាថែទាំសុខភាព ប្រឹក្សាយោបល់ សេវាផ្លូវច្បាប់ជាដើម ដោយគ្មានឧបសគ្គរារាំង។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិរួចផុតពីការបៀតបៀនផ្លូវភេទគ្រប់រូបភាព ដូចមានចែងនៅក្នុងអនុសញ្ញា CEDAW និងច្បាប់នានានៅក្នុងប្រទេសគោលដៅ។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិការងារ​សំខាន់ៗ​ដូចជា កិច្ចសន្យាការងារច្បាស់លាស់ ទទួលបានប្រាក់ឈ្នួលស្មើរគ្នា ក្នុងលក្ខខណ្ឌការងារដូចគ្នា។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិទទួលបានសុខភាព និងសុវត្ថិភាពការងារដូចគ្នា។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិទទួលបានការឈប់សម្រាកប្រចាំឆ្នាំ ឈប់សម្រាកបុណ្យជាតិ ឈប់សម្រាកពេលសម្រាលកូន ដោយទទួលបានប្រាក់ឈ្នួលជាធម្មតា។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិទទួលបានសំណង និងការឈប់សម្រាកពីគ្រោះថ្នាក់ការងារ។ </li>\n\n<li>ពលករចំណាកស្រុកជាស្ត្រី មានសិទ្ធិទទួលបានក្នុងការចូលរួមជាសមាជិកសមាគមន៍ ឬសហជីព។</li>\n</ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/24/your_right_and_safety.png",
    "audio_url": "/uploads/categories/safety/audio/24/c2_1_5_your_right_and_protection.mp3",
    "parent_id": 19,
    "uuid": "sa_001_5",
    "leaf": true,
    "lft": 46,
    "rgt": 47,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_right_and_safety.png'),
    "audio": "c2_1_5_your_right_and_protection.mp3",
    "offline": true
  },
  {
    "id": 25,
    "name": "ផែនការសុវត្ថិភាព",
    "description": null,
    "image_url": "/uploads/categories/safety/image/25/safety_planning_tips.png",
    "audio_url": "/uploads/categories/safety/audio/25/c2_2_safety_plan.mp3",
    "parent_id": null,
    "uuid": "sa_002",
    "leaf": false,
    "lft": 49,
    "rgt": 58,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_planning_tips.png'),
    "audio": "c2_2_safety_plan.mp3",
    "offline": true
  },
  {
    "id": 26,
    "name": "ប្រសិនបើអ្នកត្រូវចាកចេញភ្លាមៗ",
    "description": "<div>\n  <div>តើ​អ្នក​នឹង​ត្រូវ​ការ​អ្វីខ្លះ?​ ប្រសិន​ជា​អ្នក​តម្រូវ​ឱ្យ​ចាក​ចេញ​បន្ទាន់?</div>\n\n  <ul>\n    <li>ប្រសិន​បើ​អ្នក​ត្រូវ​ ឬសម្រេច​ចិត្ត​ចាក​ចេញ​ក្នុង​ស្ថានភាព​បន្ទាន់​ វា​ជា​រឿង​សំខាន់​ណាស់​ដែល​អ្នក​ត្រូវ​គិត​គូរ​ពី​លុយ​កាក់​ ទ្រព្យ​ធន​ ឯកសារ​សំខាន់​ និង​សំភារៈ​មួយ​ចំនួន​ដែល​អ្នក​នឹង​ត្រូវការ។</li>\n    <li>ការសន្សំ​លុយ​ និង​លាក់​វា​នៅ​កន្លែង​ណា​មួយ​ដែល​អ្នក​អាច​យក​បាន​យ៉ាង​លឿន​ និង​ងាយ​ស្រួល​ ប្រសិន​បើ​អ្នក​ត្រូវ​ចាក​ចេញ​ដោយ​ប្រញាប់។​ វា​អាច​ជា​លុយ​ កាតអេធីអ៊ីម​ (កាត​សម្រាប់​ដក​លុយ​ដោយ​ស្វ័យប្រវត្តិ)​ ដែល​អ្នក​ត្រូវ​មាន​សម្រាប់​ចំណាយ​លើ​ថ្លៃ​ធ្វើ​ដំណើរ​ និង​ចំណាយ​ផ្សេងៗ។​ គិត​ដល់​មិត្ត​ ឬអ្នក​ជិត​ខាង​ដែល​អាច​ជួយ​បញ្ចូល​លុយ​ ទូរស័ព្ទ​អោយ​អ្នក​នៅ​ពេល​ត្រូវ​ការ​ប្រើ​បន្ទាន់។</li>\n    <li>រក្សា​ទុក​អត្តសញ្ញាណប័ណ្ណ​ ឬលិខិត​ឆ្លង​ដែន​របស់​អ្នក​ និង​កូន​នៅ​កន្លែង​ដែល​លាក់​បាំង​ដែល​អាច​យក​បាន​ភ្លាមៗ។</li>\n    <li>ស្តុក​ទុក​នូវ​របស់​ដែល​អ្នក​ត្រូវ​ការ​ដូច​ជា​ អាហារ​ សំល្លៀកបំពាក់​ជា​ដើម​ ដែល​អ្នក​ងាយ​ស្រួល​យក​បាន។</li>\n    <li>វេច​ខ្ចប់​កាតាប​សង្គ្រោះ​បន្ទាន់​សម្រាប់​ខ្លួន​អ្នក​ និង​លាក់​វា​នៅ​កន្លែង​មាន​សុវត្ថិភាព​នៅ​ផ្ទះ​អ្នក​ជិត​ខាង​ ឬមិត្តភក្តិ​ដែល​អាច​ជឿ​ទុក​ចិត្ត​បាន។</li>\n    <li>បិទ​ការ​តាម​ដាន​ទីតាំង​ក្នុង​ទូរស័ព្ទ​ និង​ឧបករណ៍​អេឡិចត្រូនិច​ផ្សេងៗ​របស់​អ្នក​ដែល​មាន​មុខងារ​ស្វែងរក​ទី​តាំង​របស់​អ្នក​ បើ​សិន​ជា​អ្នក​គិត​ថា​ត្រូវ​ចាក​ចេញ។ ត្រូវ​ចង់​ចាំ​ថា​វា​អាច​ឱ្យ​អ្នក​ប្រព្រឹត្ត​អំពើ​រំលោភ​បំពាន​លើ​អ្នក​តាម​ដាន​អ្នក​តាម​ប្រព័ន្ធ​អនឡាញ​បាន។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/26/urgent_leave.png",
    "audio_url": "/uploads/categories/safety/audio/26/c2_2_1_if_need_to_leave_immediately.mp3",
    "parent_id": 25,
    "uuid": "sa_002_1",
    "leaf": true,
    "lft": 50,
    "rgt": 51,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/urgent_leave.png'),
    "audio": "c2_2_1_if_need_to_leave_immediately.mp3",
    "offline": true
  },
  {
    "id": 27,
    "name": "របស់របរដែលត្រូវរៀបចំ",
    "description": "<div>\n  <div>របស់ដែលត្រូវវេចខ្ចប់ក្នុងកាតាបសង្គ្រោះបន្ទាន់របស់អ្នក</div>\n\n  <ul>\n    <li>អត្តសញ្ញាណប័ណ្ណ រួមទាំងរូបថតមួយចំនួន</li>\n    <li>លិខិតឆ្លងដែន លិខិតអនុញ្ញាតការងារ ទិដ្ឋាការ</li>\n    <li>ធានារ៉ាប់រង និងឯកសារសំខាន់ៗផ្សេងៗទៀត។</li>\n    <li>សោរសាគួរសម្រាប់ផ្ទះ ឡាន និងកន្លែងធ្វើការរបស់អ្នក</li>\n    <li>លុយ កាតអេធីអ៊ីម (កាតសម្រាប់ដកលុយដោយស្វ័យប្រវត្តិ)</li>\n    <li>សំល្លៀកបំពាក់បន្ថែម និងខោអាវក្នុង</li>\n    <li>សំឡីអនាម័យ ឬខោទឹកនោមសម្រាប់កូនៗ</li>\n    <li>ខ្សែសាកទូរស័ព្ទ ហើយបើអាច កាតបញ្ចូលទូរស័ព្ទដែលអាចប្រើបានក្នុងពេលមានអាសន្ន</li>\n    <li>ថ្នាំមួយចំនួនដែលអ្នក និងកូនអ្នកប្រើជាប្រចាំ</li>\n    <li>លេខទូរស័ព្ទសំខាន់ៗ</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/27/checklist.png",
    "audio_url": "/uploads/categories/safety/audio/27/c2_2_2_things_to_prepare.mp3",
    "parent_id": 25,
    "uuid": "sa_002_2",
    "leaf": true,
    "lft": 52,
    "rgt": 53,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/checklist.png'),
    "audio": "c2_2_2_things_to_prepare.mp3",
    "offline": true
  },
  {
    "id": 28,
    "name": "ចំនុចដែលគួរដឹង",
    "description": "<div>\n  <div>អ្វី​ដែល​អ្នក​ត្រូវ​ដឹង​បើ​អ្នក​ជា​ស្រ្តី​ពលករ​ចំណាក​ស្រុក</div>\n\n  <ul>\n    <li>អ្នក​មាន​សិទ្ធ​ទទួល​បាន​សុវត្ថិភាព​ និង​ការពារ​ ទោះបី​ជា​អ្នក​មិន​មែន​ជា​ប្រជាពលរដ្ឋ​នៅ​ក្នុង​ប្រទេស​អ្នក​កំពុង​រស់​នៅ​ ឬកំពុង​ធ្វើ​ការ​ក៏​ដោយ។</li>\n    <li>ទាក់ទង​ក្រុម​ស្ត្រី​ ឬ​អង្គការ​ស្ត្រី​ ទូរស័ព្ទ​ទាន់​ហេតុការណ៍​ មន្រ្តី​ប៉ូលីស​ ស្ថានទូត​ សហជីព​ពាណិជ្ជកម្ម​ មជ្ឈមណ្ឌល​ពលករ​ចំណាក​ស្រុក​ គ្លីនិក​សុខភាព​ ឬ​សេវា​ផ្សេងៗ​ដែល​អ្នក​ត្រូវ​ការ។</li>\n    <li>ស្នើ​សុំ​សេវា​បកប្រែ​ពេល​អ្នក​ស្វែង​រក​សេវា​ទូរស័ព្ទ​ជំនួយ​ ប៉ូលីស​ មន្ទីរពេទ្យ​ ឬ​សេវា​ផ្សេងៗ​ទៀត។</li>\n    <li>ភ្ជាប់​ទំនាក់​ទំនង​ជា​មួយ​បណ្តាញ​ជួយ​មិត្ត​ (ក្រុមស្ត្រី​ ឬអង្គការស្ត្រី)​ ដែល​អាច​ផ្តល់​ព័ត៌មាន​និង​ភ្ជាប់​អ្នក​ទៅ​រក​សេវា​ផ្សេងៗ។</li>\n    <li>រក្សា​ទុក​លេខ​ទូរស័ព្ទ​ស្ថានទូត​ និង​កុងស៊ុល​ ពួក​គេ​នៅ​ទី​នោះ​ដើម្បី​ជួយ​អ្នក​នៅ​ក្រៅ​ប្រទេស។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/28/thing_need_to_know.png",
    "audio_url": "/uploads/categories/safety/audio/28/c2_2_3_things_to_understanding.mp3",
    "parent_id": 25,
    "uuid": "sa_002_3",
    "leaf": true,
    "lft": 54,
    "rgt": 55,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/thing_need_to_know.png'),
    "audio": "c2_2_3_things_to_understanding.mp3",
    "offline": true
  },
  {
    "id": 29,
    "name": "យុទ្ធសាស្រ្តដើម្បីសុវត្ថិភាពផ្សេងទៀត",
    "description": "<div>\n  <ul>\n    <li>មានពាក្យសម្ងាត់ ឬសញ្ញាសម្គាល់ ឬឃ្លាសុវត្ថិភាពសំរាប់ប្រើជាមួយមិត្តភក្តិ ឬក្រុមគ្រួសាររបស់អ្នកដើម្បីសុំជំនួយបន្ទាន់ពេលដែលត្រូវការ ដោយមិនចាំបាច់និយាយដោយត្រង់។</li>\n    <li>ស្វែងរកមើលថា តើមានជនណាមួយដែលជនប្រព្រឹត្តគោរព និងមានឥទ្ធិពលលើជនប្រព្រឹត្ត ហើយអាចនិយាយជាមួយគេឱ្យឈប់ប្រើអំពើហិង្សា។ ទោះបីជា រយៈពេលខ្លីក៏ដោយ។</li>\n    <li>កុំនៅស្ងៀម ឬលាក់បាំង រកសេវាជំនួយពីអាជ្ញាធរមានសមត្ថកិច្ច មន្ត្រីនគរបាល មនុស្សដែលអ្នកជឿ ឬអ្នកដឹកនាំសាសនា ឬអ្នកផ្សេងទៀត។</li>\n  </ul>\n</div>",
    "image_url": "/uploads/categories/safety/image/29/safety_more_strategy.png",
    "audio_url": "/uploads/categories/safety/audio/29/c2_2_4_other_safety_strategy.mp3",
    "parent_id": 25,
    "uuid": "sa_002_4",
    "leaf": true,
    "lft": 56,
    "rgt": 57,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_more_strategy.png'),
    "audio": "c2_2_4_other_safety_strategy.mp3",
    "offline": true
  },
  {
    "id": 30,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/30/your_safety_videos.png",
    "audio_url": "/uploads/categories/safety/audio/30/video.mp3",
    "parent_id": null,
    "uuid": "sa_003",
    "leaf": true,
    "lft": 59,
    "rgt": 60,
    "type": "Categories::Safety",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_videos.png'),
    "audio": "video.mp3",
    "offline": true
  }
]
