export default [
  {
    "id": 1,
    "name": "រៀបចំដំណើររបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/1/before_you_go_prepare_your_trip.png",
    "audio_url": "/uploads/categories/departure/audio/1/prepare_your_trip.mp3",
    "parent_id": null,
    "uuid": "de_001",
    "leaf": false,
    "lft": 1,
    "rgt": 14,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំមុនចេញដំណើរ",
    "hint_image_url": "/uploads/categories/departure/hint_image/1/6_thing_before_you_go_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/1/six_thing_before_you_go_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_prepare_your_trip.png'),
    "audio": "prepare_your_trip.mp3",
    "hint_image": require('../../assets/images/category/6_thing_before_you_go_hint.png'),
    "hint_audio": "six_thing_before_you_go_hint.mp3",
    "offline": true
  },
  {
    "id": 2,
    "name": "លិខិតឆ្លងដែន",
    "description": null,
    "image_url": "/uploads/categories/departure/image/2/pre_departure_list_passport.png",
    "audio_url": "/uploads/categories/departure/audio/2/passport.mp3",
    "parent_id": 1,
    "uuid": "de_001_1",
    "leaf": true,
    "lft": 2,
    "rgt": 3,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_passport.png'),
    "audio": "passport.mp3",
    "offline": true
  },
  {
    "id": 3,
    "name": "ទិដ្ឋាការ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/3/pre_departure_list_visa.png",
    "audio_url": "/uploads/categories/departure/audio/3/visa.mp3",
    "parent_id": 1,
    "uuid": "de_001_2",
    "leaf": true,
    "lft": 4,
    "rgt": 5,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_visa.png'),
    "audio": "visa.mp3",
    "offline": true
  },
  {
    "id": 4,
    "name": "ប័ណ្ណការងារ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/4/pre_departure_list_work_permit.png",
    "audio_url": "/uploads/categories/departure/audio/4/work_permit.mp3",
    "parent_id": 1,
    "uuid": "de_001_3",
    "leaf": true,
    "lft": 6,
    "rgt": 7,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_work_permit.png'),
    "audio": "work_permit.mp3",
    "offline": true
  },
  {
    "id": 5,
    "name": "ប្រភេទមធ្យោបាយធ្វើដំណើរ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/5/pre_departure_list_transportation.png",
    "audio_url": "/uploads/categories/departure/audio/5/transportation.mp3",
    "parent_id": 1,
    "uuid": "de_001_4",
    "leaf": true,
    "lft": 8,
    "rgt": 9,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_transportation.png'),
    "audio": "transportation.mp3",
    "offline": true
  },
  {
    "id": 6,
    "name": "ទំនាក់ទំនងជាមួយអ្នកផ្ទះ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/6/pre_departure_list_contact_with_home.png",
    "audio_url": "/uploads/categories/departure/audio/6/contact_with_home.mp3",
    "parent_id": 1,
    "uuid": "de_001_5",
    "leaf": true,
    "lft": 10,
    "rgt": 11,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contact_with_home.png'),
    "audio": "contact_with_home.mp3",
    "offline": true
  },
  {
    "id": 7,
    "name": "លេខ ឬអាស័យដ្ឋានទំនាក់ទំនង",
    "description": null,
    "image_url": "/uploads/categories/departure/image/7/pre_departure_list_contract_address.png",
    "audio_url": "/uploads/categories/departure/audio/7/contact_address.mp3",
    "parent_id": 1,
    "uuid": "de_001_6",
    "leaf": true,
    "lft": 12,
    "rgt": 13,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/pre_departure_list_contract_address.png'),
    "audio": "contact_address.mp3",
    "offline": true
  },
  {
    "id": 8,
    "name": "ចំណាកស្រុក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/8/before_you_go_migration.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_002",
    "leaf": false,
    "lft": 15,
    "rgt": 26,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចគួររៀបចំសម្រាប់ចំណាកស្រុក",
    "hint_image_url": "/uploads/categories/departure/hint_image/8/5_thing_migration_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/8/five_thing_migration_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_migration.png'),
    "hint_image": require('../../assets/images/category/5_thing_migration_hint.png'),
    "hint_audio": "five_thing_migration_hint.mp3",
    "offline": true
  },
  {
    "id": 9,
    "name": "ចាប់ផ្តើមចេញដំណើរ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/9/journey_start.png",
    "audio_url": "/uploads/categories/departure/audio/9/migration_journey_start.mp3",
    "parent_id": 8,
    "uuid": "de_002_1",
    "leaf": true,
    "lft": 16,
    "rgt": 17,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/journey_start.png'),
    "audio": "migration_journey_start.mp3",
    "offline": true
  },
  {
    "id": 10,
    "name": "ស្វែងយល់អំពីកិច្ចសន្យាការងារ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/10/migration_understanding_your_contract.png",
    "audio_url": "/uploads/categories/departure/audio/10/migration_understanding_your_contract.mp3",
    "parent_id": 8,
    "uuid": "de_002_2",
    "leaf": true,
    "lft": 18,
    "rgt": 19,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_understanding_your_contract.png'),
    "audio": "migration_understanding_your_contract.mp3",
    "offline": true
  },
  {
    "id": 11,
    "name": "សិទ្ធិពលករចំណាកស្រុក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/11/migration_worker_right.png",
    "audio_url": "/uploads/categories/departure/audio/11/migration_worker_right.mp3",
    "parent_id": 8,
    "uuid": "de_002_3",
    "leaf": true,
    "lft": 20,
    "rgt": 21,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/migration_worker_right.png'),
    "audio": "migration_worker_right.mp3",
    "offline": true
  },
  {
    "id": 12,
    "name": "វប្បធម៌ និងការរស់នៅ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/12/culture_and_living.png",
    "audio_url": "/uploads/categories/departure/audio/12/migration_calture_and_living.mp3",
    "parent_id": 8,
    "uuid": "de_002_4",
    "leaf": true,
    "lft": 22,
    "rgt": 23,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/culture_and_living.png'),
    "audio": "migration_calture_and_living.mp3",
    "offline": true
  },
  {
    "id": 13,
    "name": "គន្លឹះក្នុងការសន្សំប្រាក់",
    "description": null,
    "image_url": "/uploads/categories/departure/image/13/money_saving_tip.png",
    "audio_url": "/uploads/categories/departure/audio/13/migration_saving_tip.mp3",
    "parent_id": 8,
    "uuid": "de_002_5",
    "leaf": true,
    "lft": 24,
    "rgt": 25,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/money_saving_tip.png'),
    "audio": "migration_saving_tip.mp3",
    "offline": true
  },
  {
    "id": 14,
    "name": "ដំណើរវិលត្រឡប់",
    "description": null,
    "image_url": "/uploads/categories/departure/image/14/before_you_go_coming_home.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_003",
    "leaf": false,
    "lft": 27,
    "rgt": 34,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": "ចំនុចដើម្បីរៀបចំវិលត្រឡប់មកស្រុកវិញ",
    "hint_image_url": "/uploads/categories/departure/hint_image/14/3_things_coming_home_hint.png",
    "hint_audio_url": "/uploads/categories/departure/hint_audio/14/three_thing_coming_home_hint.mp3",
    "image": require('../../assets/images/category/before_you_go_coming_home.png'),
    "hint_image": require('../../assets/images/category/3_things_coming_home_hint.png'),
    "hint_audio": "three_thing_coming_home_hint.mp3",
    "offline": true
  },
  {
    "id": 15,
    "name": "រៀបចំផែនការរបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/departure/image/15/coming_home_make_your_plan.png",
    "audio_url": "/uploads/categories/departure/audio/15/coming_home_prepare_plan.mp3",
    "parent_id": 14,
    "uuid": "de_003_1",
    "leaf": true,
    "lft": 28,
    "rgt": 29,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_make_your_plan.png'),
    "audio": "coming_home_prepare_plan.mp3",
    "offline": true
  },
  {
    "id": 16,
    "name": "ត្រឡប់ចូលក្នុងគ្រួសារ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/16/coming_home_women_migrant_worker.png",
    "audio_url": "/uploads/categories/departure/audio/16/coming_home_back_home.mp3",
    "parent_id": 14,
    "uuid": "de_003_2",
    "leaf": true,
    "lft": 30,
    "rgt": 31,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker.png'),
    "audio": "coming_home_back_home.mp3",
    "offline": true
  },
  {
    "id": 17,
    "name": "ស្រ្តីពលករចំណាកស្រុក និងចូលរួមចំណែកក្នុងសេដ្ឋកិច្ច",
    "description": null,
    "image_url": "/uploads/categories/departure/image/17/coming_home_women_migrant_worker_and_economic.png",
    "audio_url": null,
    "parent_id": 14,
    "uuid": "de_003_3",
    "leaf": true,
    "lft": 32,
    "rgt": 33,
    "type": "Categories::Departure",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/coming_home_women_migrant_worker_and_economic.png'),
    "offline": true
  },
  {
    "id": 18,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/departure/image/18/before_you_go_video.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "de_004",
    "leaf": true,
    "lft": 35,
    "rgt": 36,
    "type": "Categories::Departure",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/before_you_go_video.png'),
    "offline": true
  },
  {
    "id": 19,
    "name": "សិទ្ធិ និងសុវត្ថិភាពរបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/safety/image/19/your_safety_safety_planning.png",
    "audio_url": "/uploads/categories/safety/audio/19/right_and_your_safety.mp3",
    "parent_id": null,
    "uuid": "sa_001",
    "leaf": false,
    "lft": 37,
    "rgt": 48,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_safety_planning.png'),
    "audio": "right_and_your_safety.mp3",
    "offline": true
  },
  {
    "id": 20,
    "name": "អំពើហិង្សាលើស្រ្តី",
    "description": null,
    "image_url": "/uploads/categories/safety/image/20/violence_on_women.png",
    "audio_url": "/uploads/categories/safety/audio/20/violence_on_women.mp3",
    "parent_id": 19,
    "uuid": "sa_001_1",
    "leaf": true,
    "lft": 38,
    "rgt": 39,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/violence_on_women.png'),
    "audio": "violence_on_women.mp3",
    "offline": true
  },
  {
    "id": 21,
    "name": "ការបៀតបៀនផ្លូវភេទ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/21/harassment.png",
    "audio_url": "/uploads/categories/safety/audio/21/harassment.mp3",
    "parent_id": 19,
    "uuid": "sa_001_2",
    "leaf": true,
    "lft": 40,
    "rgt": 41,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/harassment.png'),
    "audio": "harassment.mp3",
    "offline": true
  },
  {
    "id": 22,
    "name": "សុខភាពរបស់អ្នក",
    "description": null,
    "image_url": "/uploads/categories/safety/image/22/your_health.png",
    "audio_url": "/uploads/categories/safety/audio/22/your_health.mp3",
    "parent_id": 19,
    "uuid": "sa_001_3",
    "leaf": true,
    "lft": 42,
    "rgt": 43,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_health.png'),
    "audio": "your_health.mp3",
    "offline": true
  },
  {
    "id": 23,
    "name": "ស្វែងយល់អំពីការកេងប្រវញ្ច័​និងការជួញដូរ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/23/understand_exploitation_and_human_traficking.png",
    "audio_url": "/uploads/categories/safety/audio/23/understand__exploitation_and_human_traficking.mp3",
    "parent_id": 19,
    "uuid": "sa_001_4",
    "leaf": true,
    "lft": 44,
    "rgt": 45,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/understand_exploitation_and_human_traficking.png'),
    "audio": "understand_exploitation_and_human_traficking.mp3",
    "offline": true
  },
  {
    "id": 24,
    "name": "សិទ្ធិរបស់អ្នក និងកិច្ចគាំពារ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/24/your_right_and_safety.png",
    "audio_url": null,
    "parent_id": 19,
    "uuid": "sa_001_5",
    "leaf": true,
    "lft": 46,
    "rgt": 47,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_right_and_safety.png'),
    "offline": true
  },
  {
    "id": 25,
    "name": "ផែនការសុវត្ថិភាព",
    "description": null,
    "image_url": "/uploads/categories/safety/image/25/safety_planning_tips.png",
    "audio_url": "/uploads/categories/safety/audio/25/my_body_my_choice_safety_planning_tips.mp3",
    "parent_id": null,
    "uuid": "sa_002",
    "leaf": false,
    "lft": 49,
    "rgt": 58,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_planning_tips.png'),
    "audio": "my_body_my_choice_safety_planning_tips.mp3",
    "offline": true
  },
  {
    "id": 26,
    "name": "ប្រសិនបើអ្នកត្រូវចាកចេញភ្លាមៗ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/26/urgent_leave.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_1",
    "leaf": true,
    "lft": 50,
    "rgt": 51,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/urgent_leave.png'),
    "offline": true
  },
  {
    "id": 27,
    "name": "របស់របរដែលត្រូវរៀបចំ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/27/checklist.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_2",
    "leaf": true,
    "lft": 52,
    "rgt": 53,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/checklist.png'),
    "offline": true
  },
  {
    "id": 28,
    "name": "ចំនុចដែលគួរដឹង",
    "description": null,
    "image_url": "/uploads/categories/safety/image/28/thing_need_to_know.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_3",
    "leaf": true,
    "lft": 54,
    "rgt": 55,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/thing_need_to_know.png'),
    "offline": true
  },
  {
    "id": 29,
    "name": "យុទ្ធសាស្រ្តដើម្បីសុវត្ថិភាពផ្សេងទៀត",
    "description": null,
    "image_url": "/uploads/categories/safety/image/29/safety_more_strategy.png",
    "audio_url": null,
    "parent_id": 25,
    "uuid": "sa_002_4",
    "leaf": true,
    "lft": 56,
    "rgt": 57,
    "type": "Categories::Safety",
    "is_video": null,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/safety_more_strategy.png'),
    "offline": true
  },
  {
    "id": 30,
    "name": "វីដេអូ",
    "description": null,
    "image_url": "/uploads/categories/safety/image/30/your_safety_videos.png",
    "audio_url": null,
    "parent_id": null,
    "uuid": "sa_003",
    "leaf": true,
    "lft": 59,
    "rgt": 60,
    "type": "Categories::Safety",
    "is_video": true,
    "hint": null,
    "hint_image_url": null,
    "hint_audio_url": null,
    "image": require('../../assets/images/category/your_safety_videos.png'),
    "offline": true
  }
]
