import { Color, FontFamily, Style } from '../../assets/stylesheets/base_style';

export default [
  {
    title_en: 'Before you go',
    title_km: 'ដំណើរឆ្លងដែនរបស់អ្នក',
    name: 'ដំណើរឆ្លងដែនរបស់អ្នក',
    image: require('../../assets/images/icons/before_you_go.png'),
    screenName: 'YourDepartureScreen',
    imageWidth: '480',
    imageHeight: '360',
    audio: 'your_migration_02.mp3',
    backgroundColor: Color.beforeYouGoColor,
    code: 'your_departure',
  },
  {
    title_en: 'Your Safety',
    title_km: 'សុវត្ថិភាពរបស់អ្នក',
    name: 'សុវត្ថិភាពរបស់អ្នក',
    image: require('../../assets/images/icons/your_safety.png'),
    screenName: 'YourSafetyScreen',
    imageWidth: '300',
    imageHeight: '372',
    audio: 'your_safety_03.mp3',
    backgroundColor: Color.primary,
    code: 'your_safety',
  },
  {
    title_en: 'Looking for help?',
    title_km: 'ស្វែងរកជំនួយ',
    name: 'ស្វែងរកជំនួយ',
    image: require('../../assets/images/icons/looking_for_help.png'),
    screenName: 'CountriesListingScreen',
    imageWidth: '440',
    imageHeight: '344',
    audio: 'looking_for_help_05.mp3',
    backgroundColor: Color.yellow,
    code: 'find_help',
  },
  {
    title_en: 'Your Story',
    title_km: 'សាច់រឿងរបស់អ្នក',
    name: 'សាច់រឿងរបស់អ្នក',
    image: require('../../assets/images/icons/your_story.png'),
    screenName: 'YourStoryScreen',
    imageWidth: '440',
    imageHeight: '344',
    audio: 'your_story_04.mp3',
    backgroundColor: Color.pink,
    code: 'your_story',
  },
]
